from .dashboard import view_dashboard_faturamento, htmx_dashboard_dados
from .private_label_configuracoes import (
    pl_configuracoes,
    pl_htmx_conta_form,
    pl_htmx_conta_salvar,
    pl_htmx_contas_lista,
    pl_htmx_categoria_form,
    pl_htmx_categoria_salvar,
    pl_htmx_categorias_lista,
    pl_htmx_centro_custo_form,
    pl_htmx_centro_custo_salvar,
    pl_htmx_centros_custo_lista,
    pl_htmx_contato_form,
    pl_htmx_contato_salvar,
    pl_htmx_contatos_lista,
    pl_htmx_forma_pagamento_form,
    pl_htmx_forma_pagamento_salvar,
    pl_htmx_formas_pagamento_lista,
    pl_htmx_recorrencia_form,
    pl_htmx_recorrencia_salvar,
    pl_htmx_recorrencia_pausar,
    pl_htmx_recorrencias_lista,
)
from .private_label_lancamentos import (
    pl_home,
    pl_lancamentos,
    pl_htmx_lancamentos_lista,
    pl_htmx_lancamento_form,
    pl_htmx_lancamento_salvar,
    pl_htmx_lancamento_duplicar,
    pl_htmx_lancamento_cancelar,
    pl_htmx_lancamento_deletar,
    pl_htmx_lancamento_detalhe,
    pl_htmx_anexo_upload,
    pl_anexo_download,
    pl_htmx_baixa_form,
    pl_htmx_baixa_salvar,
    pl_htmx_baixa_estornar,
    pl_htmx_baixa_lote,
    pl_htmx_baixa_lote_form,
    pl_htmx_lancamento_deletar_lote,
    pl_htmx_lancamento_deletar_lote_form,
    pl_htmx_transferencia_form,
    pl_htmx_transferencia_salvar,
    pl_htmx_transferencia_estornar,
    pl_htmx_ajuste_saldo_form,
    pl_htmx_ajuste_saldo_salvar,
)
from .private_label_dashboard import pl_dashboard
from .private_label_cartoes import (
    pl_cartoes,
    pl_htmx_cartoes_lista,
    pl_htmx_cartao_form,
    pl_htmx_cartao_salvar,
    pl_htmx_compra_cartao_form,
    pl_htmx_compra_cartao_salvar,
    pl_htmx_compra_cartao_cancelar,
    pl_cartao_detalhe,
    pl_htmx_cartao_detalhe_conteudo,
    pl_htmx_fatura_pagar_form,
    pl_htmx_fatura_pagar_salvar,
    pl_htmx_fatura_pagamento_estornar,
)
from .private_label_fluxo_caixa import pl_fluxo_caixa
from .private_label_dre import pl_dre, pl_dre_exportar_csv
from .private_label_investimentos import (
    pl_investimentos,
    pl_htmx_investimentos_lista,
    pl_htmx_conta_investimento_form,
    pl_htmx_conta_investimento_salvar,
    pl_htmx_investimento_transacao_form,
    pl_htmx_investimento_transacao_salvar,
    pl_htmx_investimento_transacao_estornar,
)
from .private_label_conciliacao import (
    pl_conciliacao,
    pl_conciliacao_detalhe,
    pl_htmx_conciliacao_detalhe_conteudo,
    pl_htmx_conciliacao_confirmar,
    pl_htmx_conciliacao_rejeitar,
    pl_htmx_conciliacao_desfazer,
    pl_htmx_item_ignorar,
    pl_htmx_item_vincular_form,
    pl_htmx_item_vincular_salvar,
)
