# Generated by Django 5.1.15 on 2026-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=15, verbose_name='Gateway')),
                ('gateway_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='ID no gateway')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=15, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('forma', models.CharField(max_length=20, verbose_name='Forma')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas')),
                ('dados_retorno', models.JSONField(blank=True, default=dict, verbose_name='Dados retorno gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
