# Generated by Django 5.1.15 on 2026-09-01 16:42

import apps.financeiro.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('ambos', 'Cliente e Fornecedor')], default='fornecedor', max_length=12)),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contato Financeiro',
                'verbose_name_plural': 'Contatos Financeiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OperacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operação Financeira',
                'verbose_name_plural': 'Operações Financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('natureza', models.CharField(choices=[('receita', 'Receita'), ('deducao', 'Dedução / imposto sobre venda'), ('custo', 'Custo direto'), ('despesa_operacional', 'Despesa operacional'), ('receita_financeira', 'Receita financeira'), ('despesa_financeira', 'Despesa financeira'), ('fora_do_dre', 'Fora do DRE')], max_length=25)),
                ('icone', models.CharField(blank=True, help_text='Glifo/emoji — sem lib de ícone nova', max_length=10)),
                ('cor', models.CharField(default='#c9a96e', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='financeiro.categoriafinanceira')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da conta')),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('carteira_digital', 'Carteira Digital'), ('caixa', 'Caixa / Dinheiro')], default='corrente', max_length=20)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta_mascarada', models.CharField(blank=True, max_length=30, verbose_name='Conta (mascarada)')),
                ('cor', models.CharField(default='#c9a96e', max_length=7, verbose_name='Cor')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_saldo_inicial', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('incluir_consolidado', models.BooleanField(default=True, verbose_name='Incluir no saldo consolidado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_bancarias_criadas', to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AjusteSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Com sinal: positivo ou negativo', max_digits=12)),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_saldo', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_saldo', to='financeiro.contabancaria')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_saldo', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Ajuste de Saldo',
                'verbose_name_plural': 'Ajustes de Saldo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('conta_pagar', 'Conta a pagar'), ('conta_receber', 'Conta a receber')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_competencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=60)),
                ('observacoes', models.TextField(blank=True)),
                ('estado_estrutural', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_cancelados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.centrocusto')),
                ('conta_prevista', models.ForeignKey(blank=True, help_text='Opcional — conta sugerida na baixa. A conta real fica em cada Baixa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_previstos', to='financeiro.contabancaria')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contatofinanceiro')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.formapagamento')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data_vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.financeiro.models.caminho_anexo_financeiro)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(help_text='Bytes')),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_financeiros', to=settings.AUTH_USER_MODEL)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Anexo Financeiro',
                'verbose_name_plural': 'Anexos Financeiros',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='contatofinanceiro',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='financeiro.operacaofinanceira'),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('estado_estrutural', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['lancamento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_movimentado', models.DecimalField(decimal_places=2, help_text='= valor_principal + juros + multa - desconto, calculado no service', max_digits=12)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('estornada', models.BooleanField(default=False)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_estornadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_feitas', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.contabancaria')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.formapagamento')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcela')),
            ],
            options={
                'verbose_name': 'Baixa',
                'verbose_name_plural': 'Baixas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegraRecorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tipo_lancamento', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('conta_pagar', 'Conta a pagar'), ('conta_receber', 'Conta a receber')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequencia', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=12)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('quantidade_ocorrencias', models.PositiveIntegerField(blank=True, null=True)),
                ('janela_meses', models.PositiveIntegerField(default=12)),
                ('janela_gerada_ate', models.DateField(blank=True, null=True)),
                ('ultima_verificacao_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('pausada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.centrocusto')),
                ('conta_prevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.contabancaria')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.contatofinanceiro')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_recorrencia_criadas', to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.formapagamento')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_recorrencia', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Regra de Recorrência',
                'verbose_name_plural': 'Regras de Recorrência',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaRecorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_recorrencia', to='financeiro.lancamentofinanceiro')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='financeiro.regrarecorrencia')),
            ],
            options={
                'verbose_name': 'Ocorrência de Recorrência',
                'verbose_name_plural': 'Ocorrências de Recorrência',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='TagFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Tag Financeira',
                'verbose_name_plural': 'Tags Financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lancamentos', to='financeiro.tagfinanceira'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('estornada', models.BooleanField(default=False)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='financeiro.contabancaria')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_saida', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_estornadas', to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Com sinal: + entrada, - saída', max_digits=12)),
                ('evento_chave', models.CharField(max_length=80, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.ajustesaldo')),
                ('baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.baixa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.contabancaria')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.operacaofinanceira')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.transferencia')),
            ],
            options={
                'verbose_name': 'Movimento de Conta',
                'verbose_name_plural': 'Movimentos de Conta',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoriaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=40)),
                ('objeto_id', models.PositiveIntegerField()),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('cancelamento', 'Cancelamento'), ('baixa', 'Baixa'), ('estorno', 'Estorno'), ('ajuste', 'Ajuste'), ('conciliacao', 'Conciliação')], max_length=15)),
                ('campo', models.CharField(blank=True, max_length=60)),
                ('valor_de', models.CharField(blank=True, max_length=255)),
                ('valor_para', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_financeiros', to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Log de Auditoria Financeira',
                'verbose_name_plural': 'Logs de Auditoria Financeira',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['entidade', 'objeto_id'], name='financeiro__entidad_39e5aa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('natureza__in', ['receita', 'deducao', 'custo', 'despesa_operacional', 'receita_financeira', 'despesa_financeira', 'fora_do_dre'])), name='categoria_financeira_natureza_valida'),
        ),
        migrations.AddConstraint(
            model_name='ajustesaldo',
            constraint=models.CheckConstraint(condition=models.Q(('valor', 0), _negated=True), name='ajuste_saldo_valor_diferente_de_zero'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['data_vencimento', 'estado_estrutural'], name='financeiro__data_ve_8328f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcela',
            constraint=models.UniqueConstraint(fields=('lancamento', 'numero'), name='parcela_numero_unico_por_lancamento'),
        ),
        migrations.AddConstraint(
            model_name='parcela',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='parcela_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='baixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_principal__gt', 0)), name='baixa_valor_principal_positivo'),
        ),
        migrations.AddConstraint(
            model_name='baixa',
            constraint=models.CheckConstraint(condition=models.Q(('juros__gte', 0)), name='baixa_juros_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='baixa',
            constraint=models.CheckConstraint(condition=models.Q(('multa__gte', 0)), name='baixa_multa_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='baixa',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='baixa_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='baixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_movimentado__gte', 0)), name='baixa_valor_movimentado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='regrarecorrencia',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='regra_recorrencia_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ocorrenciarecorrencia',
            constraint=models.UniqueConstraint(fields=('regra', 'data_ocorrencia'), name='ocorrencia_recorrencia_unica_por_data'),
        ),
        migrations.AddConstraint(
            model_name='tagfinanceira',
            constraint=models.UniqueConstraint(fields=('operacao', 'nome'), name='tag_financeira_unica_por_operacao'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['operacao', 'data_competencia'], name='financeiro__operaca_9fb258_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['operacao', 'data_vencimento'], name='financeiro__operaca_2a49e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='lancamento_valor_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='transferencia_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('conta_origem', models.F('conta_destino')), _negated=True), name='transferencia_contas_diferentes'),
        ),
        migrations.AddIndex(
            model_name='movimentoconta',
            index=models.Index(fields=['conta', 'data'], name='financeiro__conta_i_b73f61_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('valor', 0), _negated=True), name='movimento_conta_valor_diferente_de_zero'),
        ),
        migrations.AddConstraint(
            model_name='movimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('baixa__isnull', False), ('transferencia__isnull', True), ('ajuste__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', False), ('ajuste__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', False)), _connector='OR'), name='movimento_conta_exatamente_uma_origem'),
        ),
    ]
