# Generated by Django 5.1.15 on 2026-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_seed_dados_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regrarecorrencia',
            name='tipo_lancamento',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20),
        ),
    ]
