# Generated by Django 5.1.15 on 2026-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_unifica_tipo_despesa_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoriafinanceiro',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('cancelamento', 'Cancelamento'), ('baixa', 'Baixa'), ('estorno', 'Estorno'), ('ajuste', 'Ajuste'), ('conciliacao', 'Conciliação'), ('exclusao', 'Exclusão definitiva')], max_length=15),
        ),
    ]
