# Generated by Django 5.1.15 on 2026-09-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_logauditoriafinanceiro_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='conta_prevista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_previstas', to='financeiro.contabancaria'),
        ),
    ]
