# Generated by Django 5.1.15 on 2026-09-05 17:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_parcela_conta_prevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do cartão')),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('final', models.CharField(blank=True, max_length=4, verbose_name='Final do cartão')),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_fechamento', models.PositiveSmallIntegerField()),
                ('dia_vencimento', models.PositiveSmallIntegerField()),
                ('cor', models.CharField(default='#c9a96e', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_compra', models.DateField()),
                ('parcelas_qtd', models.PositiveIntegerField(default=1)),
                ('numero_documento', models.CharField(blank=True, max_length=60)),
                ('observacoes', models.TextField(blank=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra no Cartão',
                'verbose_name_plural': 'Compras no Cartão',
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_ano', models.PositiveIntegerField()),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('estado_estrutural', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fatura de Cartão',
                'verbose_name_plural': 'Faturas de Cartão',
                'ordering': ['-competencia_ano', '-competencia_mes'],
            },
        ),
        migrations.CreateModel(
            name='FaturaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('estornado', models.BooleanField(default=False)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pagamento de Fatura',
                'verbose_name_plural': 'Pagamentos de Fatura',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaturaPagamentoAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Alocação de Pagamento de Fatura',
                'verbose_name_plural': 'Alocações de Pagamento de Fatura',
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompraCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paga_valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Parcela de Compra no Cartão',
                'verbose_name_plural': 'Parcelas de Compra no Cartão',
                'ordering': ['compra', 'numero'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='movimentoconta',
            name='movimento_conta_exatamente_uma_origem',
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='conta_pagamento_padrao',
            field=models.ForeignKey(blank=True, help_text='Conta sugerida ao pagar a fatura — só previsão, não obriga nada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_pagos_por_padrao', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cartao_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='financeiro.cartaocredito'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='financeiro.contatofinanceiro'),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cartao_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compracartao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cartao', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='faturacartao',
            name='cartao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='financeiro.cartaocredito'),
        ),
        migrations.AddField(
            model_name='faturapagamento',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_fatura', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='faturapagamento',
            name='estornado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_fatura_estornados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faturapagamento',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.faturacartao'),
        ),
        migrations.AddField(
            model_name='faturapagamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_fatura_feitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoconta',
            name='fatura_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.faturapagamento'),
        ),
        migrations.AddConstraint(
            model_name='movimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('baixa__isnull', False), ('transferencia__isnull', True), ('ajuste__isnull', True), ('fatura_pagamento__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', False), ('ajuste__isnull', True), ('fatura_pagamento__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', False), ('fatura_pagamento__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', True), ('fatura_pagamento__isnull', False)), _connector='OR'), name='movimento_conta_exatamente_uma_origem'),
        ),
        migrations.AddField(
            model_name='faturapagamentoalocacao',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='financeiro.faturapagamento'),
        ),
        migrations.AddField(
            model_name='parcelacompracartao',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.compracartao'),
        ),
        migrations.AddField(
            model_name='parcelacompracartao',
            name='fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.faturacartao'),
        ),
        migrations.AddField(
            model_name='faturapagamentoalocacao',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes_pagamento', to='financeiro.parcelacompracartao'),
        ),
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.CheckConstraint(condition=models.Q(('limite_total__gt', 0)), name='cartao_limite_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.CheckConstraint(condition=models.Q(('dia_fechamento__gte', 1), ('dia_fechamento__lte', 28)), name='cartao_dia_fechamento_valido'),
        ),
        migrations.AddConstraint(
            model_name='cartaocredito',
            constraint=models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 28)), name='cartao_dia_vencimento_valido'),
        ),
        migrations.AddIndex(
            model_name='compracartao',
            index=models.Index(fields=['cartao', 'data_compra'], name='financeiro__cartao__a30b3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='compracartao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compra_cartao_valor_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compracartao',
            constraint=models.CheckConstraint(condition=models.Q(('parcelas_qtd__gte', 1)), name='compra_cartao_parcelas_qtd_minima'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'competencia_ano', 'competencia_mes'), name='fatura_cartao_unica_por_competencia'),
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.CheckConstraint(condition=models.Q(('competencia_mes__gte', 1), ('competencia_mes__lte', 12)), name='fatura_cartao_competencia_mes_valido'),
        ),
        migrations.AddConstraint(
            model_name='faturapagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fatura_pagamento_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacompracartao',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='parcela_compra_cartao_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='parcelacompracartao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='parcela_compra_cartao_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacompracartao',
            constraint=models.CheckConstraint(condition=models.Q(('paga_valor__gte', 0)), name='parcela_compra_cartao_paga_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='parcelacompracartao',
            constraint=models.CheckConstraint(condition=models.Q(('paga_valor__lte', models.F('valor'))), name='parcela_compra_cartao_paga_valor_nao_excede_valor'),
        ),
        migrations.AddConstraint(
            model_name='faturapagamentoalocacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fatura_pagamento_alocacao_valor_positivo'),
        ),
    ]
