# Generated by Django 5.1.15 on 2026-09-05 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_cartaocredito_compracartao_faturacartao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('instituicao', models.CharField(blank=True, max_length=120)),
                ('tipo_produto', models.CharField(choices=[('cdb', 'CDB'), ('tesouro_direto', 'Tesouro Direto'), ('fundo', 'Fundo de Investimento'), ('poupanca', 'Poupança'), ('acoes', 'Ações'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta de Investimento',
                'verbose_name_plural': 'Contas de Investimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InvestimentoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aplicacao', 'Aplicação'), ('resgate', 'Resgate'), ('rendimento', 'Rendimento'), ('taxa', 'Taxa/Imposto')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('estornada', models.BooleanField(default=False)),
                ('estornada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transação de Investimento',
                'verbose_name_plural': 'Transações de Investimento',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContaInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Com sinal: + cresce, - diminui', max_digits=12)),
                ('evento_chave', models.CharField(max_length=80, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimento de Conta de Investimento',
                'verbose_name_plural': 'Movimentos de Conta de Investimento',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='movimentoconta',
            name='movimento_conta_exatamente_uma_origem',
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_investimento_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_investimento', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Obrigatória para rendimento/taxa (natureza financeira); não se aplica a aplicação/resgate.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_investimento', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Obrigatória para aplicação/resgate; não se aplica a rendimento/taxa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_investimento', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='conta_investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.containvestimento'),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='estornada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_investimento_estornadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_investimento', to='financeiro.operacaofinanceira'),
        ),
        migrations.AddField(
            model_name='investimentotransacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_investimento_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentoconta',
            name='investimento_transacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_conta_bancaria', to='financeiro.investimentotransacao'),
        ),
        migrations.AddConstraint(
            model_name='movimentoconta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('baixa__isnull', False), ('transferencia__isnull', True), ('ajuste__isnull', True), ('fatura_pagamento__isnull', True), ('investimento_transacao__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', False), ('ajuste__isnull', True), ('fatura_pagamento__isnull', True), ('investimento_transacao__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', False), ('fatura_pagamento__isnull', True), ('investimento_transacao__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', True), ('fatura_pagamento__isnull', False), ('investimento_transacao__isnull', True)), models.Q(('baixa__isnull', True), ('transferencia__isnull', True), ('ajuste__isnull', True), ('fatura_pagamento__isnull', True), ('investimento_transacao__isnull', False)), _connector='OR'), name='movimento_conta_exatamente_uma_origem'),
        ),
        migrations.AddField(
            model_name='movimentocontainvestimento',
            name='conta_investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.containvestimento'),
        ),
        migrations.AddField(
            model_name='movimentocontainvestimento',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.investimentotransacao'),
        ),
        migrations.AddConstraint(
            model_name='investimentotransacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='investimento_transacao_valor_positivo'),
        ),
        migrations.AddIndex(
            model_name='movimentocontainvestimento',
            index=models.Index(fields=['conta_investimento', 'data'], name='financeiro__conta_i_e2e782_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentocontainvestimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor', 0), _negated=True), name='movimento_conta_investimento_valor_diferente_de_zero'),
        ),
    ]
