# Generated by Django 5.1.15 on 2026-09-05 18:16

import apps.financeiro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_containvestimento_investimentotransacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.financeiro.models.caminho_extrato_financeiro)),
                ('nome_original', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('ofx', 'OFX'), ('csv', 'CSV')], max_length=3)),
                ('hash_arquivo', models.CharField(max_length=64, unique=True)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='financeiro.contabancaria')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_extrato_feitas', to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_extrato', to='financeiro.operacaofinanceira')),
            ],
            options={
                'verbose_name': 'Importação de Extrato',
                'verbose_name_plural': 'Importações de Extrato',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('identificador_externo', models.CharField(blank=True, help_text='Identificador único da transação no banco, quando o OFX traz um (FITID). Vazio em CSV.', max_length=80, verbose_name='FITID (OFX)')),
                ('hash_transacao', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conciliado', 'Conciliado'), ('ignorado', 'Ignorado')], default='pendente', max_length=10)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.importacaoextrato')),
            ],
            options={
                'verbose_name': 'Item de Extrato',
                'verbose_name_plural': 'Itens de Extrato',
                'ordering': ['-data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_confianca', models.CharField(blank=True, choices=[('alta', 'Alta (mesma data e valor)'), ('media', 'Média (valor igual, data próxima)'), ('manual', 'Manual')], max_length=8)),
                ('status', models.CharField(choices=[('sugerido', 'Sugerido'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='sugerido', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desfeita_em', models.DateTimeField(blank=True, null=True)),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.movimentoconta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('item_extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='financeiro.itemextrato')),
            ],
            options={
                'verbose_name': 'Conciliação',
                'verbose_name_plural': 'Conciliações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='itemextrato',
            index=models.Index(fields=['importacao', 'status'], name='financeiro__importa_df3dd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemextrato',
            constraint=models.CheckConstraint(condition=models.Q(('valor', 0), _negated=True), name='item_extrato_valor_diferente_de_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemextrato',
            constraint=models.UniqueConstraint(fields=('importacao', 'hash_transacao'), name='item_extrato_hash_unico_por_importacao'),
        ),
    ]
