# Generated by Django 5.1.15 on 2026-09-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_importacaoextrato_itemextrato_conciliacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaCDIDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('taxa_pct_dia', models.DecimalField(decimal_places=6, help_text='Taxa do CDI daquele dia útil, em % ao dia (ex.: 0.051660).', max_digits=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taxa CDI Diária',
                'verbose_name_plural': 'Taxas CDI Diárias',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='categoria_rendimento',
            field=models.ForeignKey(blank=True, help_text="Categoria usada nos lançamentos automáticos de rendimento (natureza 'Receita financeira').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_investimento_rendimento_auto', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='liquidez',
            field=models.CharField(blank=True, choices=[('diaria', 'Diária'), ('vencimento', 'No vencimento'), ('carencia', 'Com carência')], help_text='Só informativo — não afeta o cálculo de rendimento.', max_length=12),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='percentual_cdi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex.: 98.00 para 98% do CDI. Deixe vazio se o produto não é indexado ao CDI.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='rendimento_automatico',
            field=models.BooleanField(default=False, help_text='Se marcado, o rendimento de cada dia útil é lançado sozinho (CDI oficial do Banco Central x percentual_cdi) — cron `calcular_rendimento_investimentos`.'),
        ),
        migrations.AlterField(
            model_name='containvestimento',
            name='tipo_produto',
            field=models.CharField(choices=[('cdb', 'CDB'), ('dcb', 'DCB'), ('tesouro_direto', 'Tesouro Direto'), ('fundo', 'Fundo de Investimento'), ('poupanca', 'Poupança'), ('acoes', 'Ações'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='containvestimento',
            constraint=models.CheckConstraint(condition=models.Q(('rendimento_automatico', False), models.Q(('percentual_cdi__isnull', False), ('categoria_rendimento__isnull', False)), _connector='OR'), name='investimento_auto_exige_percentual_e_categoria'),
        ),
    ]
