# Generated by Django 5.1.15 on 2026-09-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_taxacdidiaria_containvestimento_categoria_rendimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containvestimento',
            name='categoria_iof',
            field=models.ForeignKey(blank=True, help_text="Categoria usada no lançamento automático de IOF no resgate (natureza 'Despesa financeira').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_investimento_iof_auto', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='iof_automatico',
            field=models.BooleanField(default=False, help_text='Se marcado, todo resgate calcula sozinho o IOF regressivo (tabela oficial da Receita, incide só sobre o rendimento, isento a partir do 30º dia corrido de cada aplicação) e já lança a taxa — ver `services/private_label/investimentos.py::_calcular_iof_resgate`.'),
        ),
        migrations.AddConstraint(
            model_name='containvestimento',
            constraint=models.CheckConstraint(condition=models.Q(('iof_automatico', False), ('categoria_iof__isnull', False), _connector='OR'), name='investimento_iof_auto_exige_categoria'),
        ),
    ]
