# Generated by Django 5.1.15 on 2026-09-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_containvestimento_categoria_iof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentotransacao',
            name='transacao_origem',
            field=models.ForeignKey(blank=True, help_text='Preenchido só no IOF automático de resgate: aponta pro resgate que o gerou — estornar o resgate também estorna esse IOF junto (ver `estornar_transacao`).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxas_derivadas', to='financeiro.investimentotransacao'),
        ),
    ]
