# Generated by Django 5.1.15 on 2026-09-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_investimentotransacao_transacao_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containvestimento',
            name='categoria_ir',
            field=models.ForeignKey(blank=True, help_text="Categoria usada no lançamento automático de IR no resgate (natureza 'Despesa financeira').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_investimento_ir_auto', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='containvestimento',
            name='ir_automatico',
            field=models.BooleanField(default=False, help_text='Se marcado, todo resgate calcula sozinho o IR pela tabela regressiva de renda fixa (22,5% até 180 dias, 20% até 360, 17,5% até 720, 15% acima disso — sobre o rendimento já líquido de IOF) e já lança a taxa — ver `services/private_label/investimentos.py::_calcular_impostos_resgate`.'),
        ),
        migrations.AddConstraint(
            model_name='containvestimento',
            constraint=models.CheckConstraint(condition=models.Q(('ir_automatico', False), ('categoria_ir__isnull', False), _connector='OR'), name='investimento_ir_auto_exige_categoria'),
        ),
    ]
