# Generated by Django 5.1.15 on 2026-06-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('gclid', models.CharField(blank=True, max_length=300)),
                ('fbclid', models.CharField(blank=True, max_length=300)),
                ('dispositivo', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_acao_em', models.DateTimeField(auto_now=True, db_index=True)),
                ('total_paginas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sessao Analytics',
                'verbose_name_plural': 'Sessoes Analytics',
                'indexes': [models.Index(fields=['ultima_acao_em'], name='analytics_s_ultima__2fc1cc_idx'), models.Index(fields=['iniciada_em'], name='analytics_s_iniciad_ad6752_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagina_vista', 'Pagina Vista'), ('produto_visualizado', 'Produto Visualizado'), ('lista_visualizada', 'Lista Visualizada'), ('busca_realizada', 'Busca Realizada'), ('produto_adicionado', 'Produto Adicionado'), ('produto_removido', 'Produto Removido'), ('carrinho_visualizado', 'Carrinho Visualizado'), ('checkout_iniciado', 'Checkout Iniciado'), ('pagamento_selecionado', 'Pagamento Selecionado'), ('pedido_finalizado', 'Pedido Finalizado'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('wishlist_adicionado', 'Wishlist Adicionado'), ('cupom_aplicado', 'Cupom Aplicado'), ('cupom_invalido', 'Cupom Invalido')], db_index=True, max_length=30)),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pagina_url', models.CharField(blank=True, max_length=500)),
                ('produto_slug', models.CharField(blank=True, db_index=True, max_length=200)),
                ('produto_nome', models.CharField(blank=True, max_length=200)),
                ('categoria_nome', models.CharField(blank=True, max_length=100)),
                ('variacao_desc', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido_numero', models.CharField(blank=True, max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, max_length=20)),
                ('busca_termo', models.CharField(blank=True, max_length=200)),
                ('busca_resultados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=30)),
                ('cupom_codigo', models.CharField(blank=True, max_length=50)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='analytics.sessaoanalytics')),
            ],
            options={
                'verbose_name': 'Evento Analytics',
                'verbose_name_plural': 'Eventos Analytics',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['ocorrido_em'], name='analytics_e_ocorrid_0511dc_idx'), models.Index(fields=['tipo', 'ocorrido_em'], name='analytics_e_tipo_fd824f_idx'), models.Index(fields=['sessao', 'tipo'], name='analytics_e_sessao__dbf591_idx')],
            },
        ),
    ]
