# Generated by Django 5.1.15 on 2026-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_eventoanalytics_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoanalytics',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sessaoanalytics',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='sessaoanalytics',
            index=models.Index(fields=['ip_hash', 'iniciada_em'], name='analytics_s_ip_hash_43c815_idx'),
        ),
    ]
