# Generated by Django 5.1.15 on 2026-07-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sessaoanalytics_ip_hash_sessaoanalytics_is_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoanalytics',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sessaoanalytics',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
