# Generated by Django 5.1.15 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_sessaoanalytics_cidade_sessaoanalytics_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoanalytics',
            name='tipo',
            field=models.CharField(choices=[('pagina_vista', 'Pagina Vista'), ('produto_visualizado', 'Produto Visualizado'), ('lista_visualizada', 'Lista Visualizada'), ('busca_realizada', 'Busca Realizada'), ('produto_adicionado', 'Produto Adicionado'), ('produto_removido', 'Produto Removido'), ('carrinho_visualizado', 'Carrinho Visualizado'), ('checkout_iniciado', 'Checkout Iniciado'), ('popup_saida_exibido', 'Popup de Saida Exibido'), ('pagamento_selecionado', 'Pagamento Selecionado'), ('pedido_finalizado', 'Pedido Finalizado'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('wishlist_adicionado', 'Wishlist Adicionado'), ('cupom_aplicado', 'Cupom Aplicado'), ('cupom_invalido', 'Cupom Invalido'), ('link_bio_clicado', 'Link da Bio Clicado')], db_index=True, max_length=30),
        ),
    ]
