# Generated by Django 5.1.15 on 2026-08-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_eventoanalytics_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoanalytics',
            name='utm_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
