# Generated by Django 5.1.15 on 2026-09-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0020_vtvalorvigencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('lalamove', 'Lalamove'), ('loggi', 'Loggi')], default='lalamove', max_length=10)),
                ('status', models.CharField(choices=[('aguardando_coleta', 'Aguardando Coleta'), ('no_percurso', 'No Percurso'), ('entrega_realizada', 'Entrega Realizada'), ('problema_entrega', 'Problema na Entrega'), ('problema_coleta', 'Problema na Coleta')], default='aguardando_coleta', max_length=20)),
                ('endereco_retirada', models.CharField(max_length=255)),
                ('endereco_entrega', models.CharField(max_length=255)),
                ('remetente', models.CharField(max_length=120)),
                ('destinatario', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('lalamove_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('lalamove_quotation_id', models.CharField(blank=True, max_length=64)),
                ('lalamove_status_raw', models.CharField(blank=True, help_text='Último status bruto recebido da Lalamove, antes de traduzir para STATUS_CHOICES.', max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data/hora do pedido.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, help_text='Quando chegou a um status final.', null=True)),
                ('colaborador', models.ForeignKey(help_text='Quem pediu a corrida (não quem só aprovou/lançou).', on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_entrega', to='rh.colaborador')),
                ('solicitado_por', models.ForeignKey(blank=True, help_text='Login que efetivamente confirmou o pedido no painel (pode ser diferente do colaborador, ex: financeiro lançando por outra pessoa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_entrega_lancadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Entrega',
                'verbose_name_plural': 'Solicitações de Entrega',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEntregaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('status_raw', models.CharField(blank=True, max_length=40)),
                ('origem', models.CharField(default='webhook', help_text='webhook | manual | polling', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='motoqueiro.solicitacaoentrega')),
            ],
            options={
                'verbose_name': 'Evento de Entrega',
                'verbose_name_plural': 'Eventos de Entrega',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaoentrega',
            index=models.Index(fields=['criado_em'], name='motoqueiro__criado__2b1bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoentrega',
            index=models.Index(fields=['colaborador', 'criado_em'], name='motoqueiro__colabor_6f8c4e_idx'),
        ),
    ]
