# Generated by Django 5.1.15 on 2026-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial (venda)'), ('producao', 'Produção')], help_text='Se o frete é de venda (comercial) ou de produção — escolhido na confirmação da corrida.', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lat_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lat_retirada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lng_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lng_retirada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
