# Generated by Django 5.1.15 on 2026-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0002_solicitacaoentrega_finalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='veiculo',
            field=models.CharField(blank=True, help_text='Ex: LalaGo (moto sem baú), LalaPro (moto com baú) — qual tipo/veículo foi escolhido na cotação.', max_length=60),
        ),
    ]
