# Generated by Django 5.1.15 on 2026-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0003_solicitacaoentrega_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lalamove_share_link',
            field=models.URLField(blank=True, help_text='Link de rastreio ao vivo (mapa + motoboy) que a Lalamove devolve ao criar o pedido.', max_length=500),
        ),
    ]
