# Generated by Django 5.1.15 on 2026-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0004_solicitacaoentrega_lalamove_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoentrega',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('producao', 'Produção')], help_text='Se o frete é de venda (comercial) ou de produção — escolhido na confirmação da corrida.', max_length=10),
        ),
    ]
