# Generated by Django 5.1.15 on 2026-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0005_alter_solicitacaoentrega_finalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='complemento_entrega',
            field=models.CharField(blank=True, help_text='Bloco, apto, andar, ponto de referência.', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='complemento_retirada',
            field=models.CharField(blank=True, help_text='Bloco, apto, andar, ponto de referência.', max_length=100),
        ),
    ]
