# Generated by Django 5.1.15 on 2026-09-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0006_solicitacaoentrega_complemento_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoSaldoLalamove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito (recarga)'), ('debito', 'Débito (saída)')], max_length=10)),
                ('origem', models.CharField(choices=[('manual', 'Lançamento manual'), ('corrida', 'Corrida solicitada pelo sistema')], default='manual', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, help_text="Sempre positivo — o campo 'tipo' define a direção.", max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lancado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, help_text='Preenchido só quando origem=corrida (débito automático).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_saldo', to='motoqueiro.solicitacaoentrega')),
            ],
            options={
                'verbose_name': 'Movimento de Saldo Lalamove',
                'verbose_name_plural': 'Movimentos de Saldo Lalamove',
                'ordering': ['-criado_em'],
            },
        ),
    ]
