# Generated by Django 5.1.15 on 2026-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0007_movimentosaldolalamove'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='loggi_key',
            field=models.CharField(blank=True, help_text='Identificador definitivo do pacote devolvido pela Loggi (loggiKey).', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='loggi_label_url',
            field=models.URLField(blank=True, help_text='Link da etiqueta (PDF) gerada para a corrida.', max_length=500),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='loggi_status_raw',
            field=models.CharField(blank=True, help_text='Último código de status bruto recebido da Loggi, antes de traduzir para STATUS_CHOICES.', max_length=40),
        ),
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='loggi_tracking_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código de rastreio — usado para consultar status e cancelar.', max_length=100),
        ),
    ]
