# Generated by Django 5.1.15 on 2026-09-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0008_solicitacaoentrega_loggi_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoentrega',
            name='status',
            field=models.CharField(choices=[('aguardando_coleta', 'Aguardando Coleta'), ('no_percurso', 'No Percurso'), ('entrega_realizada', 'Entrega Realizada'), ('problema_entrega', 'Problema na Entrega'), ('problema_coleta', 'Problema na Coleta'), ('cancelado', 'Cancelada')], default='aguardando_coleta', max_length=20),
        ),
    ]
