# Generated by Django 5.1.15 on 2026-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0009_alter_solicitacaoentrega_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoentrega',
            name='lalamove_prioridade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa de prioridade em vigor (não é acumulada: o último valor substitui o anterior). Teto de R$ 10.', max_digits=6),
        ),
    ]
