# Generated by Django 5.1.15 on 2026-09-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0010_solicitacaoentrega_lalamove_prioridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_retirada', models.CharField(max_length=255)),
                ('complemento_retirada', models.CharField(blank=True, max_length=100)),
                ('lat_retirada', models.FloatField()),
                ('lng_retirada', models.FloatField()),
                ('endereco_entrega', models.CharField(max_length=255)),
                ('complemento_entrega', models.CharField(blank=True, max_length=100)),
                ('lat_entrega', models.FloatField()),
                ('lng_entrega', models.FloatField()),
                ('veiculo', models.CharField(choices=[('qualquer', 'Qualquer um (o mais barato)'), ('LALAGO', 'LalaGo (moto, sem baú)'), ('LALAPRO', 'LalaPro (moto com baú)')], default='qualquer', max_length=10)),
                ('preco_alvo', models.DecimalField(decimal_places=2, help_text='Avisa quando algum veículo cotar igual ou abaixo disso.', max_digits=8)),
                ('status', models.CharField(choices=[('ativo', 'Monitorando'), ('encontrado', 'Preço encontrado'), ('expirado', 'Expirado sem achar'), ('cancelado', 'Cancelado')], default='ativo', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(help_text='Horário (no mesmo dia da criação) em que o monitoramento para sozinho, mesmo sem achar o preço.')),
                ('ultima_consulta_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_preco_lalago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ultimo_preco_lalapro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ultimo_erro', models.CharField(blank=True, help_text='Última falha ao cotar (rota recusada, API fora etc.) — só informativo, não para o monitoramento.', max_length=255)),
                ('encontrado_em', models.DateTimeField(blank=True, null=True)),
                ('preco_encontrado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('veiculo_encontrado', models.CharField(blank=True, max_length=60)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoramentos_cotacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoramento de Cotação',
                'verbose_name_plural': 'Monitoramentos de Cotação',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'expira_em'], name='motoqueiro__status_0e84fc_idx')],
            },
        ),
    ]
