# Generated by Django 5.1.15 on 2026-08-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriosemanal',
            name='aguardando_pagamento',
            field=models.IntegerField(default=0, verbose_name='Pedidos aguardando pagamento'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='analise_ia',
            field=models.TextField(blank=True, default='', verbose_name='Analise da IA'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='carrinhos_abandonados',
            field=models.IntegerField(default=0, verbose_name='Carrinhos abandonados'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='checkouts_abandonados',
            field=models.IntegerField(default=0, verbose_name='Checkouts abandonados'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='itens_vendidos',
            field=models.IntegerField(default=0, verbose_name='Itens vendidos'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='paginas_vistas',
            field=models.IntegerField(default=0, verbose_name='Paginas vistas'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='pedidos_pagos',
            field=models.IntegerField(default=0, verbose_name='Vendas pagas'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='receita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita total'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='taxa_conversao',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Taxa de conversao (%)'),
        ),
        migrations.AddField(
            model_name='relatoriosemanal',
            name='visitantes',
            field=models.IntegerField(default=0, verbose_name='Visitantes unicos'),
        ),
    ]
