# Generated by Django 5.1.15 on 2026-08-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_relatoriosemanal_aguardando_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.URLField(max_length=600, unique=True, verbose_name='Destino')),
                ('canal', models.CharField(max_length=60, verbose_name='Canal')),
                ('url_curta', models.URLField(blank=True, max_length=300, verbose_name='Link curto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Gerado',
                'verbose_name_plural': 'Links Gerados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
