# Generated by Django 5.1.15 on 2026-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_linkgerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkgerado',
            name='pagina',
            field=models.URLField(blank=True, max_length=600, verbose_name='Pagina (sem UTM)'),
        ),
        migrations.AlterField(
            model_name='linkgerado',
            name='destino',
            field=models.URLField(max_length=600, unique=True, verbose_name='Destino (com UTM)'),
        ),
    ]
