# Generated by Django 5.1.15 on 2026-04-13 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_set', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_set', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item da wishlist',
                'verbose_name_plural': 'Wishlist',
                'ordering': ['-adicionado_em'],
                'unique_together': {('cliente', 'produto')},
            },
        ),
    ]
