# Generated by Django 5.1.15 on 2026-04-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-adicionado_em'], 'verbose_name': 'Lista de desejos (produto salvo)', 'verbose_name_plural': 'Listas de desejos (produtos salvos)'},
        ),
    ]
