# Generated by Django 5.1.15 on 2026-04-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_wishlist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precisa_ativar',
            field=models.BooleanField(default=False, verbose_name='Precisa ativar conta'),
        ),
    ]
