# Generated by Django 5.1.15 on 2026-05-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_precisa_ativar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_codigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de verificação admin',
                'verbose_name_plural': 'Códigos de verificação admin',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AdminVerificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_verificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificação admin',
                'verbose_name_plural': 'Verificações admin',
            },
        ),
    ]
