# Generated by Django 5.1.15 on 2026-04-13 14:11

import apps.produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_publico', models.CharField(max_length=80, verbose_name='Nome')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nota')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('comentario', models.TextField(blank=True, max_length=800, verbose_name='Comentário')),
                ('aprovada', models.BooleanField(default=False, verbose_name='Aprovada')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, max_length=500, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='categorias/', verbose_name='Imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem no menu')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('composicao', models.CharField(blank=True, max_length=200, verbose_name='Composição/Material')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('U', 'Unissex')], default='F', max_length=1, verbose_name='Gênero')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na home')),
                ('novo', models.BooleanField(default=True, verbose_name='Novo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('bling_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID Bling')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='SKU')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=apps.produtos.models.produto_imagem_path, verbose_name='Imagem')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens do produto',
                'ordering': ['-principal', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tamanho', 'Tamanho'), ('cor', 'Cor')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('codigo_hex', models.CharField(blank=True, max_length=7, verbose_name='Cor hex')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('sku_variacao', models.CharField(blank=True, max_length=80, verbose_name='SKU variação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
