# Generated by Django 5.1.15 on 2026-04-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'ordering': ['cor', 'tamanho'], 'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='produto',
            name='seo_descricao',
            field=models.TextField(blank=True, help_text='Descrição para Google (máx. 160 caracteres). Se vazia, usa o início da descrição do produto.', max_length=160, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='produto',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Separadas por vírgula. Ex: body preto, lingerie premium.', max_length=200, verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='produto',
            name='seo_titulo',
            field=models.CharField(blank=True, help_text='Título para Google (máx. 70 caracteres). Se vazio, usa o nome do produto.', max_length=70, verbose_name='Título SEO'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='bling_variacao_id',
            field=models.CharField(blank=True, help_text='ID do produto filho desta variação no Bling.', max_length=50, verbose_name='ID Bling'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='cor',
            field=models.CharField(blank=True, help_text='Ex: Preto, Branco, Rosa. Deixe vazio se o produto não tem variação de cor.', max_length=50, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='tamanho',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, GG, 38, 40. Deixe vazio se o produto não tem tamanho.', max_length=20, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='bling_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID do produto pai no Bling. Cada variação tem seu próprio SKU e ID.', max_length=50, verbose_name='ID Bling (produto pai)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU base/referência. O SKU individual fica em cada variação.', max_length=80, verbose_name='SKU base'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='codigo_hex',
            field=models.CharField(blank=True, help_text='Código hex da cor para exibir a bolinha colorida. Ex: #000000', max_length=7, verbose_name='Hex da cor'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='sku_variacao',
            field=models.CharField(blank=True, db_index=True, help_text='SKU individual desta variação no Bling. Ex: 100', max_length=80, verbose_name='SKU'),
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='tipo',
        ),
    ]
