# Generated by Django 5.1.15 on 2026-04-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_corpadrao_tamanhopadrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpadrao',
            name='codigo_hex',
            field=models.CharField(blank=True, help_text='Ex: #000000 — usado para exibir a bolinha colorida no site.', max_length=7, verbose_name='Código hex'),
        ),
        migrations.AlterField(
            model_name='corpadrao',
            name='nome',
            field=models.CharField(help_text='Ex: Preto, Branco, Rosa Chá', max_length=50, unique=True, verbose_name='Nome da cor'),
        ),
        migrations.AlterField(
            model_name='tamanhopadrao',
            name='nome',
            field=models.CharField(help_text='Ex: P, M, G, GG, 38, 40', max_length=20, unique=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='tamanhopadrao',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primeiro. Ex: PP=0, P=1, M=2, G=3, GG=4', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='cor',
            field=models.ForeignKey(blank=True, help_text='Selecione da lista. Cadastre novas cores em Produtos → Cores padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.corpadrao', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='tamanho',
            field=models.ForeignKey(blank=True, help_text='Selecione da lista. Cadastre novos tamanhos em Produtos → Tamanhos padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.tamanhopadrao', verbose_name='Tamanho'),
        ),
    ]
