# Generated by Django 5.1.15 on 2026-04-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_corpadrao_codigo_hex_alter_corpadrao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Geral', help_text='Ex: Body, Beachwear, Geral', max_length=80, verbose_name='Nome')),
                ('conteudo', models.TextField(help_text='Descreva as medidas. Pode usar texto simples ou HTML básico. Exemplo: PP: busto 82cm | cintura 62cm | quadril 88cm', verbose_name='Conteúdo da tabela')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, help_text='Deixe em branco para usar como tabela padrão geral. Se preenchida, é usada para produtos dessa categoria.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Tabela de medidas',
                'verbose_name_plural': 'Tabelas de medidas',
                'ordering': ['nome'],
            },
        ),
    ]
