# Generated by Django 5.1.15 on 2026-04-15 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_tabelamedidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpadrao',
            name='codigo_hex_secundario',
            field=models.CharField(blank=True, help_text='Opcional. Preencha para exibir bolinha com 2 cores (diagonal). Ex: produto bicolor Preto/Branco → #000000 + #FFFFFF.', max_length=7, verbose_name='Código hex secundário'),
        ),
        migrations.AlterField(
            model_name='corpadrao',
            name='codigo_hex',
            field=models.CharField(blank=True, help_text='Ex: #000000 — cor principal (ou única) da bolinha.', max_length=7, verbose_name='Código hex'),
        ),
        migrations.CreateModel(
            name='ProdutoCorFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.ForeignKey(help_text='Selecione a cor. Ao clicar nessa bolinha no site, a galeria muda para a foto abaixo.', on_delete=django.db.models.deletion.CASCADE, related_name='fotos_produto', to='produtos.corpadrao', verbose_name='Cor')),
                ('imagem', models.ForeignKey(blank=True, help_text='Escolha uma das fotos já cadastradas neste produto para representar essa cor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cor_fotos', to='produtos.produtoimagem', verbose_name='Foto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_por_cor', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto por cor',
                'verbose_name_plural': 'Fotos por cor',
                'ordering': ['cor__ordem', 'cor__nome'],
                'unique_together': {('produto', 'cor')},
            },
        ),
    ]
