# Generated by Django 5.1.15 on 2026-04-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_corpadrao_codigo_hex_secundario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Inscrição Newsletter',
                'verbose_name_plural': 'Inscrições Newsletter',
                'ordering': ['-inscrito_em'],
            },
        ),
    ]
