# Generated by Django 5.1.15 on 2026-04-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_newsletterinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_1',
            field=models.CharField(blank=True, default='P', max_length=20, verbose_name='Coluna 1'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_2',
            field=models.CharField(blank=True, default='M', max_length=20, verbose_name='Coluna 2'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_3',
            field=models.CharField(blank=True, default='G', max_length=20, verbose_name='Coluna 3'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_4',
            field=models.CharField(blank=True, default='GG', max_length=20, verbose_name='Coluna 4'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_5',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Coluna 5'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='cabecalho_6',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Coluna 6'),
        ),
        migrations.AddField(
            model_name='tabelamedidas',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Ex: Escolha o tamanho ideal', max_length=140, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='tabelamedidas',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Opcional. Mantido por compatibilidade para tabelas antigas em texto/HTML. Se voce cadastrar linhas abaixo, o site usara a tabela estruturada.', verbose_name='Conteudo legado da tabela'),
        ),
        migrations.CreateModel(
            name='TabelaMedidasLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('medida', models.CharField(max_length=80, verbose_name='Medida')),
                ('unidade', models.CharField(blank=True, help_text='Opcional. Ex: cm, kg', max_length=20, verbose_name='Unidade')),
                ('valor_1', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 1')),
                ('valor_2', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 2')),
                ('valor_3', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 3')),
                ('valor_4', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 4')),
                ('valor_5', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 5')),
                ('valor_6', models.CharField(blank=True, max_length=40, verbose_name='Valor coluna 6')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='produtos.tabelamedidas', verbose_name='Tabela')),
            ],
            options={
                'verbose_name': 'Linha da tabela',
                'verbose_name_plural': 'Linhas da tabela',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
