# Generated by Django 5.1.15 on 2026-04-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_tabela_medidas_estruturada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='tabelamedidas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tabelamedidas',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='produtos.produto', verbose_name='Produto (opcional)'),
        ),
        migrations.AlterField(
            model_name='tabelamedidas',
            name='cabecalho_5',
            field=models.CharField(blank=True, max_length=20, verbose_name='Coluna 5'),
        ),
        migrations.AlterField(
            model_name='tabelamedidas',
            name='cabecalho_6',
            field=models.CharField(blank=True, max_length=20, verbose_name='Coluna 6'),
        ),
        migrations.AlterField(
            model_name='tabelamedidas',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Opcional. Mantido por compatibilidade para tabelas antigas em texto/HTML. Se você cadastrar linhas abaixo, o site usará a tabela estruturada.', verbose_name='Conteúdo legado da tabela'),
        ),
    ]
