# Generated by Django 5.1.15 on 2026-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_categoria_nome_alter_categoria_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.PositiveSmallIntegerField(default=500, help_text='Peso da peça em gramas — usado no cálculo de frete (ex: 200, 300, 500)', verbose_name='Peso (g)'),
        ),
    ]
