# Generated by Django 5.1.15 on 2026-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_peso_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='genero',
        ),
    ]
