# Generated by Django 5.1.15 on 2026-05-03 19:28

import django.db.models.deletion
from django.db import migrations, models


def migrar_fotos_para_primeira_cor(apps, schema_editor):
    Produto = apps.get_model('produtos', 'Produto')
    ProdutoImagem = apps.get_model('produtos', 'ProdutoImagem')
    Variacao = apps.get_model('produtos', 'Variacao')

    for produto in Produto.objects.all().iterator():
        primeira_cor_id = (
            Variacao.objects
            .filter(produto_id=produto.pk, ativa=True, cor__isnull=False)
            .order_by('cor__ordem', 'cor__nome', 'pk')
            .values_list('cor_id', flat=True)
            .first()
        )
        if not primeira_cor_id:
            continue

        Produto.objects.filter(pk=produto.pk, cor_principal__isnull=True).update(cor_principal_id=primeira_cor_id)
        ProdutoImagem.objects.filter(produto_id=produto.pk, cor__isnull=True).update(cor_id=primeira_cor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_variacao_precos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoimagem',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Imagem do produto', 'verbose_name_plural': 'Imagens do produto'},
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_principal',
            field=models.ForeignKey(blank=True, help_text='Define qual cor abre a vitrine pública e fornece a foto de capa do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_capa', to='produtos.corpadrao', verbose_name='Cor principal'),
        ),
        migrations.AddField(
            model_name='produtoimagem',
            name='cor',
            field=models.ForeignKey(blank=True, help_text='Cada foto pertence a uma cor. A primeira foto da cor vira a principal daquela cor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_produto', to='produtos.corpadrao', verbose_name='Cor do produto'),
        ),
        migrations.RunPython(migrar_fotos_para_primeira_cor, migrations.RunPython.noop),
    ]
