# Generated by Django 5.1.15 on 2026-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_avaliacao_por_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='comportamento_sem_estoque',
            field=models.CharField(choices=[('indisponivel', 'Tornar indisponível'), ('sob_demanda', 'Continuar vendendo sob demanda')], default='indisponivel', help_text='Define o comportamento ao zerar o estoque (só se aplica a variações com disponibilidade imediata).', max_length=20, verbose_name='Quando acabar o estoque'),
        ),
        migrations.AddField(
            model_name='variacao',
            name='usa_sync_bling',
            field=models.BooleanField(default=False, help_text='Quando ativo, o estoque é atualizado automaticamente pelo Bling.', verbose_name='Sync estoque Bling'),
        ),
    ]
