# Generated by Django 5.1.15 on 2026-05-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_variacao_sync_bling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='composicao',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Composição/Material'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=5000, verbose_name='Descrição'),
        ),
    ]
