# Generated by Django 5.1.15 on 2026-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_descricao_max_5000'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='usa_sync_preco_bling',
            field=models.BooleanField(default=True, help_text='Quando ativo, o preço (varejo) desta variação é atualizado automaticamente pelo Bling.', verbose_name='Sync preço Bling'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='usa_sync_bling',
            field=models.BooleanField(default=True, help_text='Quando ativo, o estoque é atualizado automaticamente pelo Bling.', verbose_name='Sync estoque Bling'),
        ),
    ]
