# Generated by Django 5.1.15 on 2026-09-04 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_backfill_carrinho_pedido'),
        ('produtos', '0022_variacao_usa_sync_preco_bling_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPedidoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True, verbose_name='Atribuído em')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_responsavel', to='pedidos.pedido', verbose_name='Pedido')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_pedidos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável por avaliação de pedido',
                'verbose_name_plural': 'Responsáveis por avaliação de pedido',
                'permissions': [('gerenciar_pedidos_entregues', 'Pode gerenciar pedidos entregues x avaliação')],
            },
        ),
    ]
