# Generated by Django 5.1.15 on 2026-04-13 14:11

import apps.pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico do pedido',
                'verbose_name_plural': 'Histórico dos pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU')),
                ('variacao_desc', models.CharField(blank=True, max_length=100, verbose_name='Variação')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, default=apps.pedidos.models.gerar_numero_pedido, max_length=20, unique=True, verbose_name='Número')),
                ('nome_completo', models.CharField(max_length=240, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cep_entrega', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero_entrega', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('em_separacao', 'Em Separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], db_index=True, default='aguardando_pagamento', max_length=30, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('cartao_credito', 'Cartão de Crédito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, verbose_name='Forma de pagamento')),
                ('gateway', models.CharField(blank=True, choices=[('pagseguro', 'PagSeguro'), ('stone', 'Stone')], max_length=15, verbose_name='Gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=100, verbose_name='ID no gateway')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, verbose_name='Código de rastreio')),
                ('transportadora', models.CharField(blank=True, max_length=80, verbose_name='Transportadora')),
                ('bling_pedido_id', models.CharField(blank=True, max_length=50, verbose_name='ID pedido Bling')),
                ('bling_nfe_id', models.CharField(blank=True, max_length=50, verbose_name='ID NF-e Bling')),
                ('nfe_chave', models.CharField(blank=True, max_length=50, verbose_name='Chave NF-e')),
                ('observacao_cliente', models.TextField(blank=True, max_length=300, verbose_name='Observação do cliente')),
                ('observacao_interna', models.TextField(blank=True, max_length=500, verbose_name='Observação interna')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
