# Generated by Django 5.1.15 on 2026-04-17 03:13

import apps.pedidos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=apps.pedidos.models.gerar_codigo_vendedor, max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do vendedor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Código de vendedor',
                'verbose_name_plural': 'Códigos de vendedor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código que o cliente digita no checkout. Ex: DELLA10', max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor fixo (R$)')], default='percentual', max_length=10, verbose_name='Tipo de desconto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Percentual (ex: 10 = 10%) ou valor fixo em reais (ex: 30.00)', max_digits=10, verbose_name='Valor do desconto')),
                ('quantidade_total', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para uso ilimitado', null=True, verbose_name='Quantidade total disponível')),
                ('vezes_usado', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vezes usado')),
                ('um_por_cliente', models.BooleanField(default=True, help_text='Se marcado, o mesmo CPF só pode usar este cupom uma vez', verbose_name='Apenas 1 uso por cliente')),
                ('valido_de', models.DateField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valido_ate', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_vendedor_str',
            field=models.CharField(blank=True, help_text='Copiado no momento da compra', max_length=20, verbose_name='Código do vendedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom_codigo',
            field=models.CharField(blank=True, help_text='Copiado no momento da compra', max_length=50, verbose_name='Código do cupom'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.codigovendedor', verbose_name='Código do vendedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.cupom', verbose_name='Cupom'),
        ),
    ]
