# Generated by Django 5.1.15 on 2026-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_codigovendedor_cupom_pedido_codigo_vendedor_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_servico_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID serviço frete'),
        ),
    ]
