# Generated by Django 5.1.15 on 2026-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_frete_servico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='frete_servico_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID serviço frete'),
        ),
    ]
