# Generated by Django 5.1.15 on 2026-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_frete_servico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_prazo_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Prazo frete (dias)'),
        ),
    ]
