# Generated by Django 5.1.15 on 2026-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_frete_prazo_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigovendedor',
            name='codigo',
            field=models.CharField(help_text='Nome ou palavra-chave que identifica o vendedor. Ex: TINA', max_length=50, unique=True, verbose_name='Código / Nome'),
        ),
        migrations.AlterField(
            model_name='codigovendedor',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome completo'),
        ),
    ]
