# Generated by Django 5.1.15 on 2026-04-26 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_codigovendedor_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrinhoAbandonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=240, verbose_name='Nome')),
                ('itens_json', models.JSONField(verbose_name='Itens do carrinho')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='E-mail enviado')),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em')),
                ('recuperado', models.BooleanField(default=False, verbose_name='Recuperado (compra feita)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos_abandonados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Carrinho Abandonado',
                'verbose_name_plural': 'Carrinhos Abandonados',
                'ordering': ['-atualizado_em'],
                'unique_together': {('cliente',)},
            },
        ),
    ]
