# Generated by Django 5.1.15 on 2026-05-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_carrinhoabandonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='me_order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID pedido Melhor Envio'),
        ),
        migrations.CreateModel(
            name='RastreioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_order_id', models.CharField(db_index=True, max_length=100, verbose_name='ID ME')),
                ('evento', models.CharField(max_length=50, verbose_name='Evento')),
                ('tracking', models.CharField(blank=True, max_length=50, verbose_name='Código rastreio')),
                ('dados_raw', models.JSONField(verbose_name='Payload raw')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rastreio_eventos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Evento de Rastreio (ME)',
                'verbose_name_plural': 'Eventos de Rastreio (ME)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
