# Generated by Django 5.1.15 on 2026-05-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_me_order_id_rastreioevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correios_email_saiu_entrega',
            field=models.BooleanField(default=False, verbose_name='E-mail "saiu p/ entrega" enviado'),
        ),
    ]
