# Generated by Django 5.1.15 on 2026-05-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_avaliacao_email_enviado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correios_entregue_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o rastreio confirma entrega. Status muda p/ entregue 7 dias depois.', null=True, verbose_name='Correios: entrega detectada em'),
        ),
    ]
