# Generated by Django 5.1.15 on 2026-05-18 02:43

import apps.pedidos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_pedido_correios_entregue_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='dias_validade_pos_emissao',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Para templates de cupons emitidos individualmente (ex: newsletter): a validade é calculada por emissão. Quando preenchido, ignora "Válido a partir de" / "Válido até".', null=True, verbose_name='Dias de validade após emissão'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual (criado pelo admin)'), ('newsletter', 'Newsletter (gerado ao se inscrever)'), ('primeira_compra', 'Primeira compra'), ('aniversario', 'Aniversário')], default='manual', help_text='Manual = cupons criados aqui no admin. Os demais são templates usados para gerar cupons únicos automaticamente para cada cliente (ex: newsletter).', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(help_text='Para cupons manuais: código que o cliente digita no checkout. Ex: DELLA10. Para cupons-template (origem ≠ manual), serve apenas de referência interna.', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='gateway',
            field=models.CharField(blank=True, choices=[('pagseguro', 'PagSeguro')], max_length=15, verbose_name='Gateway'),
        ),
        migrations.CreateModel(
            name='CupomEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=apps.pedidos.models.gerar_codigo_cupom_emitido, help_text='Código único entregue à cliente. Formato DELLA-XXXXXX.', max_length=20, unique=True, verbose_name='Código')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('emitido_em', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('cupom_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emitidos', to='pedidos.cupom', verbose_name='Cupom template')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_emitidos_usados', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Cupom emitido',
                'verbose_name_plural': 'Cupons emitidos (automáticos)',
                'ordering': ['-emitido_em'],
            },
        ),
    ]
