# Generated by Django 5.1.15 on 2026-05-18

import uuid
from django.db import migrations, models


def gerar_tokens(apps, schema_editor):
    CarrinhoAbandonado = apps.get_model('pedidos', 'CarrinhoAbandonado')
    for ca in CarrinhoAbandonado.objects.filter(token__isnull=True):
        ca.token = uuid.uuid4()
        ca.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_cupom_dias_validade_pos_emissao_cupom_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoabandonado',
            name='token',
            field=models.UUIDField(null=True, editable=False, unique=False, verbose_name='Token de recuperação'),
        ),
        migrations.RunPython(gerar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='carrinhoabandonado',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de recuperação'),
        ),
    ]
