# Generated by Django 5.1.15 on 2026-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_carrinhoabandonado_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retirada_loja',
            field=models.BooleanField(default=False, verbose_name='Retirar na loja'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('em_separacao', 'Em Separação'), ('pronto_retirada', 'Pronto para Retirada'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], db_index=True, default='aguardando_pagamento', max_length=30, verbose_name='Status'),
        ),
    ]
