# Generated by Django 5.1.15 on 2026-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_retirada_loja_pronto_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='consentimento_analytics',
            field=models.BooleanField(default=False, verbose_name='Consentiu analise (GA4)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='consentimento_marketing',
            field=models.BooleanField(default=False, verbose_name='Consentiu marketing (Meta)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ga_client_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='GA4 client_id (_ga)'),
        ),
    ]
