# Generated by Django 5.1.15 on 2026-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedido_consentimento_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='capi_purchase_enviado',
            field=models.BooleanField(default=False, verbose_name='CAPI purchase enviado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fbclid',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta Click ID (fbclid)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='gclid',
            field=models.CharField(blank=True, max_length=300, verbose_name='Google Click ID (gclid)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM ID'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Term'),
        ),
    ]
