# Generated by Django 5.1.15 on 2026-07-28 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_carrinhoabandonado_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoabandonado',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinhos_abandonados', to='pedidos.pedido', verbose_name='Pedido gerado'),
        ),
        migrations.AlterField(
            model_name='carrinhoabandonado',
            name='recuperado',
            field=models.BooleanField(default=False, verbose_name='Recuperado (compra paga)'),
        ),
        migrations.AlterField(
            model_name='carrinhoabandonado',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de recuperacao'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual (criado pelo admin)'), ('newsletter', 'Newsletter (gerado ao se inscrever)'), ('primeira_compra', 'Primeira compra'), ('aniversario', 'Aniversario'), ('carrinho_popup', 'Carrinho (popup de saida)')], default='manual', help_text='Manual = cupons criados aqui no admin. Os demais são templates usados para gerar cupons únicos automaticamente para cada cliente (ex: newsletter).', max_length=20, verbose_name='Origem'),
        ),
    ]
