# Generated by Django 5.1.15 on 2026-04-14 04:42

import apps.conteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_categoria_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, help_text='1 = primeiro slide. Recomendado: ordem 1 para o vídeo.', verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('foto', 'Foto')], default='foto', max_length=5, verbose_name='Tipo')),
                ('video', models.FileField(blank=True, help_text='Somente se tipo = Vídeo. Formato MP4, ideal 1920×1080px, até 50 MB.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Vídeo (MP4)')),
                ('foto', models.ImageField(blank=True, help_text='Somente se tipo = Foto. Ideal: 1920×1080px.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Foto')),
                ('poster', models.ImageField(blank=True, help_text='Imagem exibida enquanto o vídeo carrega. Ideal: 1920×1080px.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Poster do vídeo')),
                ('pretitulo', models.CharField(blank=True, help_text='Ex: "Nova Coleção 2025"', max_length=80, verbose_name='Pré-título')),
                ('titulo', models.CharField(help_text='Ex: "Elegância que veste a alma"', max_length=120, verbose_name='Título')),
                ('titulo_italico', models.CharField(blank=True, help_text='Parte final do título que aparece em itálico/dourado.', max_length=80, verbose_name='Trecho em itálico')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('texto_botao', models.CharField(default='Explorar coleção', max_length=60, verbose_name='Texto do botão')),
                ('url_botao', models.CharField(default='/loja/', help_text='Caminho relativo. Ex: /loja/ ou /loja/bodies/', max_length=200, verbose_name='Link do botão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Slide do banner principal',
                'verbose_name_plural': 'Slides do banner principal',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MiniBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('esq', 'Esquerda'), ('dir', 'Direita')], max_length=3, unique=True, verbose_name='Posição')),
                ('foto', models.ImageField(help_text='Ideal: 900×1200px (retrato). Foco no assunto na parte inferior.', upload_to=apps.conteudo.models.mini_banner_upload_path, verbose_name='Foto')),
                ('pretitulo', models.CharField(blank=True, help_text='Ex: "Combinação de Shapes + Cores"', max_length=80, verbose_name='Pré-título')),
                ('titulo', models.CharField(help_text='Ex: "USE JUNTO"', max_length=80, verbose_name='Título')),
                ('url', models.CharField(default='/loja/', help_text='Caminho relativo. Ex: /loja/bodies/', max_length=200, verbose_name='Link')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Mini banner',
                'verbose_name_plural': 'Mini banners',
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='LookDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Look da semana', max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Texto que aparece ao lado da foto. Máx. 400 caracteres.', max_length=400, verbose_name='Descrição')),
                ('foto', models.ImageField(help_text='Ideal: 800×1100px (retrato). Exibida no lado esquerdo.', upload_to=apps.conteudo.models.look_upload_path, verbose_name='Foto do look')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(blank=True, help_text='Selecione até 3 produtos que aparecem listados ao lado da foto.', limit_choices_to={'ativo': True}, to='produtos.produto', verbose_name='Produtos do look')),
            ],
            options={
                'verbose_name': 'Look da semana',
                'verbose_name_plural': 'Looks da semana',
                'ordering': ['-criado_em'],
            },
        ),
    ]
