# Generated by Django 5.1.15 on 2026-04-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='pretitulo',
            field=models.CharField(blank=True, help_text='Opcional. Ex: "Nova Coleção 2025"', max_length=80, verbose_name='Pré-título'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='texto_botao',
            field=models.CharField(blank=True, help_text='Opcional. Ex: "Explorar coleção". Deixe vazio para não exibir botão.', max_length=60, verbose_name='Texto do botão'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional — deixe vazio se o vídeo/foto já tem o texto na imagem.', max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='url_botao',
            field=models.CharField(blank=True, default='/loja/', help_text='Caminho relativo. Ex: /loja/ ou /loja/bodies/', max_length=200, verbose_name='Link do botão'),
        ),
    ]
