# Generated by Django 5.1.15 on 2026-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_alter_bannerprincipal_pretitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto1_esq',
            field=models.DecimalField(decimal_places=1, default=42, help_text='Distância da esquerda da foto em % (0=esq, 100=dir).', max_digits=5, verbose_name='Ponto 1 — Esquerda (%)'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto1_top',
            field=models.DecimalField(decimal_places=1, default=30, help_text='Distância do topo da foto em % (0=topo, 100=base).', max_digits=5, verbose_name='Ponto 1 — Topo (%)'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto2_esq',
            field=models.DecimalField(decimal_places=1, default=55, help_text='Distância da esquerda da foto em %.', max_digits=5, verbose_name='Ponto 2 — Esquerda (%)'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto2_top',
            field=models.DecimalField(decimal_places=1, default=55, help_text='Distância do topo da foto em %.', max_digits=5, verbose_name='Ponto 2 — Topo (%)'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto3_esq',
            field=models.DecimalField(decimal_places=1, default=30, help_text='Distância da esquerda da foto em %.', max_digits=5, verbose_name='Ponto 3 — Esquerda (%)'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='ponto3_top',
            field=models.DecimalField(decimal_places=1, default=70, help_text='Distância do topo da foto em %.', max_digits=5, verbose_name='Ponto 3 — Topo (%)'),
        ),
    ]
