# Generated by Django 5.1.15 on 2026-04-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_lookdasemana_ponto1_esq_lookdasemana_ponto1_top_and_more'),
        ('produtos', '0006_alter_corpadrao_codigo_hex_alter_corpadrao_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookdasemana',
            name='produtos',
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='produto_ponto1',
            field=models.ForeignKey(blank=True, help_text='Produto que o "+" 1 aponta.', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look_ponto1', to='produtos.produto', verbose_name='Produto do ponto 1'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='produto_ponto2',
            field=models.ForeignKey(blank=True, help_text='Produto que o "+" 2 aponta.', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look_ponto2', to='produtos.produto', verbose_name='Produto do ponto 2'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='produto_ponto3',
            field=models.ForeignKey(blank=True, help_text='Produto que o "+" 3 aponta.', limit_choices_to={'ativo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look_ponto3', to='produtos.produto', verbose_name='Produto do ponto 3'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto1_esq',
            field=models.DecimalField(decimal_places=1, default=42, max_digits=5, verbose_name='Esquerda (%)'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto1_top',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=5, verbose_name='Topo (%)'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto2_esq',
            field=models.DecimalField(decimal_places=1, default=55, max_digits=5, verbose_name='Esquerda (%)'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto2_top',
            field=models.DecimalField(decimal_places=1, default=55, max_digits=5, verbose_name='Topo (%)'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto3_esq',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=5, verbose_name='Esquerda (%)'),
        ),
        migrations.AlterField(
            model_name='lookdasemana',
            name='ponto3_top',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=5, verbose_name='Topo (%)'),
        ),
    ]
