# Generated by Django 5.1.15 on 2026-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_remove_lookdasemana_produtos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_gratis_acima', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para desativar. Ex: 500.00 para frete grátis acima de R$ 500.', max_digits=10, null=True, verbose_name='Frete grátis acima de (R$)')),
            ],
            options={
                'verbose_name': 'Configuração da loja',
                'verbose_name_plural': 'Configurações da loja',
            },
        ),
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('politica_privacidade', 'Política de privacidade'), ('trocas_devolucoes', 'Trocas e devoluções'), ('sobre', 'Nossa história'), ('termos_uso', 'Termos de uso')], max_length=30, unique=True, verbose_name='Página')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('conteudo', models.TextField(help_text='Texto da página. Use quebras de linha para parágrafos. HTML básico é aceito.', verbose_name='Conteúdo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Página estática',
                'verbose_name_plural': 'Páginas estáticas',
            },
        ),
        migrations.AlterField(
            model_name='minibanner',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional — o banner já pode ter o texto na própria imagem.', max_length=80, verbose_name='Título'),
        ),
    ]
