# Generated by Django 5.1.15 on 2026-04-14 23:00

import apps.conteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0005_configuracaoloja_paginaestatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerprincipal',
            name='foto_mobile',
            field=models.ImageField(blank=True, help_text='Opcional. Versão vertical para celular. Retrato 1080×1920px (9:16).', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Foto — Mobile'),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='video_mobile',
            field=models.FileField(blank=True, help_text='Opcional. Versão vertical para celular. Retrato 1080×1920px (9:16), até 30 MB.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Vídeo (MP4) — Mobile'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='foto',
            field=models.ImageField(blank=True, help_text='Somente se tipo = Foto. Paisagem 1920×1080px.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Foto — Desktop'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='video',
            field=models.FileField(blank=True, help_text='Somente se tipo = Vídeo. Formato MP4, paisagem 1920×1080px, até 50 MB.', upload_to=apps.conteudo.models.banner_upload_path, verbose_name='Vídeo (MP4) — Desktop'),
        ),
    ]
