# Generated by Django 5.1.15 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0006_bannerprincipal_foto_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaestatica',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Usada na página "Nossa história" ao lado do texto. Proporção recomendada: 3:4.', upload_to='paginas/', verbose_name='Imagem (opcional)'),
        ),
        migrations.AlterField(
            model_name='paginaestatica',
            name='conteudo',
            field=models.TextField(help_text='Editor de texto rico — use a barra de ferramentas para formatar. Negrito, itálico, títulos, listas e links são suportados. O conteúdo é salvo como HTML.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='paginaestatica',
            name='slug',
            field=models.CharField(choices=[('politica_privacidade', 'Política de privacidade'), ('trocas_devolucoes', 'Trocas e devoluções'), ('sobre', 'Nossa história'), ('termos_uso', 'Termos de uso'), ('perguntas_frequentes', 'Perguntas frequentes'), ('meios_pagamento', 'Meios de pagamento e frete')], max_length=30, unique=True, verbose_name='Página'),
        ),
    ]
