# Generated by Django 5.1.15 on 2026-04-17 14:01

import apps.conteudo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0007_paginaestatica_imagem_alter_paginaestatica_conteudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=50, unique=True, verbose_name='ID do post')),
                ('media_type', models.CharField(default='IMAGE', max_length=20, verbose_name='Tipo')),
                ('media_url', models.URLField(max_length=1000, verbose_name='URL da imagem')),
                ('permalink', models.URLField(max_length=500, verbose_name='Link do post')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Data do post')),
                ('ativo', models.BooleanField(default=False, help_text='Marque os posts que devem aparecer na seção Instagram da homepage.', verbose_name='Exibir no site')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primeiro. Posts com a mesma ordem ficam por data.', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Post Instagram',
                'verbose_name_plural': 'Posts Instagram',
                'ordering': ['ordem', '-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='video',
            field=models.FileField(blank=True, help_text='Somente se tipo = Vídeo. Formato MP4, paisagem 1920×1080px, até 50 MB.', upload_to=apps.conteudo.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Vídeo (MP4) — Desktop'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='video_mobile',
            field=models.FileField(blank=True, help_text='Opcional. Versão vertical para celular. Retrato 1080×1920px (9:16), até 30 MB.', upload_to=apps.conteudo.models.banner_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Vídeo (MP4) — Mobile'),
        ),
    ]
