# Generated by Django 5.1.15 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0008_instagrampost_alter_bannerprincipal_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(max_length=2000, verbose_name='URL da imagem'),
        ),
    ]
