# Generated by Django 5.1.15 on 2026-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0009_alter_instagrampost_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='imagem_local',
            field=models.ImageField(blank=True, help_text='Baixada automaticamente na importação.', null=True, upload_to='instagram/', verbose_name='Imagem'),
        ),
    ]
