# Generated by Django 5.1.15 on 2026-04-24 14:27

import apps.conteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0010_remove_instagrampost_media_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoloja',
            options={'verbose_name': 'Frete Grátis', 'verbose_name_plural': 'Frete Grátis'},
        ),
        migrations.AlterModelOptions(
            name='minibanner',
            options={'ordering': ['-posicao'], 'verbose_name': 'Mini banner', 'verbose_name_plural': 'Mini banners'},
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='pretitulo',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='texto_botao',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='bannerprincipal',
            name='titulo_italico',
        ),
        migrations.RemoveField(
            model_name='minibanner',
            name='pretitulo',
        ),
        migrations.RemoveField(
            model_name='minibanner',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='url_botao',
            field=models.CharField(blank=True, default='/loja/', help_text='Caminho relativo. Ao clicar em qualquer parte do banner, redireciona para este link. Ex: /loja/ ou /loja/bodies/', max_length=200, verbose_name='Link do banner (ao clicar)'),
        ),
        migrations.AlterField(
            model_name='minibanner',
            name='foto',
            field=models.ImageField(help_text='Ideal: 900×1200px (retrato). Foco no assunto na parte superior.', upload_to=apps.conteudo.models.mini_banner_upload_path, verbose_name='Foto'),
        ),
    ]
