# Generated by Django 5.1.15 on 2026-04-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0011_alter_configuracaoloja_options_and_more'),
        ('produtos', '0014_remove_genero_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookdasemana',
            name='foto_ponto1',
            field=models.ForeignKey(blank=True, help_text='Foto específica para exibir. Se vazio, usa a foto principal do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produtos.produtoimagem', verbose_name='Foto do ponto 1'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='foto_ponto2',
            field=models.ForeignKey(blank=True, help_text='Foto específica para exibir. Se vazio, usa a foto principal do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produtos.produtoimagem', verbose_name='Foto do ponto 2'),
        ),
        migrations.AddField(
            model_name='lookdasemana',
            name='foto_ponto3',
            field=models.ForeignKey(blank=True, help_text='Foto específica para exibir. Se vazio, usa a foto principal do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produtos.produtoimagem', verbose_name='Foto do ponto 3'),
        ),
    ]
