# Generated by Django 5.1.15 on 2026-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0012_foto_ponto_look'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoloja',
            options={'verbose_name': 'Configurações da Loja', 'verbose_name_plural': 'Configurações da Loja'},
        ),
        migrations.AddField(
            model_name='configuracaoloja',
            name='modo_manutencao',
            field=models.BooleanField(default=False, help_text='Ativado: somente o admin consegue acessar o site. Visitantes veem uma página "Em breve". Desativado: site funciona normalmente.', verbose_name='Modo manutenção'),
        ),
    ]
