# Generated by Django 5.1.15 on 2026-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0015_alter_tarjafrase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerprincipal',
            name='posicao_imagem',
            field=models.CharField(choices=[('center center', 'Centralizado (padrão)'), ('left center', 'Esquerda (mostra início da foto)'), ('right center', 'Direita (mostra fim da foto)'), ('center top', 'Topo (mostra parte superior)'), ('center bottom', 'Base (mostra parte inferior)'), ('left top', 'Esquerda superior'), ('right top', 'Direita superior'), ('left bottom', 'Esquerda inferior'), ('right bottom', 'Direita inferior')], default='center center', help_text='Define qual parte da foto fica visível quando o banner é cortado pelo navegador. Use "Esquerda" se o texto/elemento principal estiver no início da foto.', max_length=14, verbose_name='Posição da imagem no banner'),
        ),
    ]
