# Generated by Django 5.1.15 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0016_bannerprincipal_posicao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('mensagem', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('observacao', models.TextField(blank=True, help_text='Anotacoes internas sobre este contato (nao visiveis ao cliente).', verbose_name='Observacao interna')),
            ],
            options={
                'verbose_name': 'Formulario de contato',
                'verbose_name_plural': 'Formularios de contato',
                'ordering': ['-recebido_em'],
            },
        ),
    ]
