# Generated by Django 5.1.15 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0017_contatoformulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Texto do botão. Ex: Nova Coleção Verão, Body mais vendido.', max_length=60, verbose_name='Título')),
                ('url', models.URLField(help_text='Para onde o botão leva. Ex: https://www.dellainstore.com/loja/lancamentos/', max_length=500, verbose_name='Link')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primeiro (logo abaixo do botão Loja online).', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder sem precisar excluir.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Link da Bio (Instagram)',
                'verbose_name_plural': 'Links da Bio (Instagram)',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
