# Generated by Django 5.1.15 on 2026-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0018_linkbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbio',
            name='icone',
            field=models.CharField(choices=[('loja', 'Loja (botão principal preto)'), ('destaque', 'Destaque (dourado)'), ('whatsapp', 'WhatsApp (ícone verde)'), ('local', 'Endereço / Mapa (pino)'), ('nenhum', 'Simples (sem ícone)')], default='nenhum', help_text='Define o ícone e o visual do botão.', max_length=10, verbose_name='Ícone / Estilo'),
        ),
        migrations.AddField(
            model_name='linkbio',
            name='nova_aba',
            field=models.BooleanField(default=True, help_text='Recomendado para WhatsApp e mapas. Desmarque para a loja/home.', verbose_name='Abrir em nova aba'),
        ),
        migrations.AddField(
            model_name='linkbio',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Linha menor abaixo do título. Ex: o endereço completo da loja. Deixe vazio se não quiser.', max_length=120, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='linkbio',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primeiro.', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='linkbio',
            name='titulo',
            field=models.CharField(help_text='Texto do botão. Ex: Loja online, WhatsApp Vendas, Nova Coleção.', max_length=60, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='linkbio',
            name='url',
            field=models.URLField(help_text='Para onde o botão leva. Ex: https://www.dellainstore.com/ ou link do Google Maps.', max_length=500, verbose_name='Link'),
        ),
    ]
