# Generated by Django 5.1.15 on 2026-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0020_linkbio_botoes_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCurto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Codigo')),
                ('destino', models.URLField(max_length=600, verbose_name='Destino')),
                ('cliques', models.PositiveIntegerField(default=0, verbose_name='Cliques')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Link Curto',
                'verbose_name_plural': 'Links Curtos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
