# Generated by Django 5.1.15 on 2026-08-10 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(blank=True, help_text='Cor hex opcional, ex.: #c9a96e', max_length=20)),
                ('eh_conclusao', models.BooleanField(default=False, help_text='Tarefas aqui não entram no contador de pendências do menu.', verbose_name='É coluna de conclusão')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coluna de status',
                'verbose_name_plural': 'Colunas de status',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('prazo', models.DateField()),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivada', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='tarefas.colunastatus')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['posicao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('criacao', 'Criação'), ('titulo', 'Título'), ('descricao', 'Descrição'), ('prioridade', 'Prioridade'), ('prazo', 'Prazo'), ('status', 'Status'), ('responsaveis', 'Responsáveis'), ('arquivada', 'Exclusão')], max_length=30)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_novo', models.CharField(blank=True, max_length=255)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Histórico de tarefa',
                'verbose_name_plural': 'Histórico de tarefas',
                'ordering': ['-alterado_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuida_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tarefa', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(related_name='tarefas_responsavel', through='tarefas.TarefaResponsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
