# Generated by Django 5.1.15 on 2026-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_seed_colunas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='editado_em',
            field=models.DateTimeField(blank=True, help_text='Só marcado quando o criador edita título/descrição/prazo/prioridade — usado pra avisar responsáveis que ainda não viram a mudança. Mover de coluna não conta como edição.', null=True),
        ),
        migrations.AddField(
            model_name='tarefaresponsavel',
            name='visto_em',
            field=models.DateTimeField(blank=True, help_text='Última vez que este responsável abriu o card — comparado com Tarefa.editado_em pra saber se ele já viu a versão mais recente.', null=True),
        ),
    ]
