# Generated by Django 5.1.15 on 2026-08-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_liberar_tarefas_todos_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='arquivada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='concluida_em',
            field=models.DateTimeField(blank=True, help_text='Quando entrou numa coluna de conclusão — zera se voltar pra uma coluna ativa. O comando arquivar_tarefas_concluidas usa isso pra saber há quantos dias está concluída.', null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='motivo_arquivamento',
            field=models.CharField(blank=True, choices=[('concluida', 'Concluída'), ('excluida', 'Excluída')], max_length=20),
        ),
    ]
