# Generated by Django 5.1.15 on 2026-08-16 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_tarefa_arquivada_em_tarefa_concluida_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaresponsavel',
            name='adicionado_por',
            field=models.ForeignKey(blank=True, help_text='Quem colocou esta pessoa como responsável — controla quem pode tirá-la depois: o criador da tarefa (ou Super Admin) tira qualquer um; um responsável só tira quem ele mesmo adicionou.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TarefaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Comentário de tarefa',
                'verbose_name_plural': 'Comentários de tarefa',
                'ordering': ['criado_em'],
            },
        ),
    ]
