# Generated by Django 5.1.15 on 2026-09-19 00:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0020_vtvalorvigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_segundos', models.IntegerField(default=10, help_text='Intervalo de consulta do frontend, em segundos.')),
                ('margem_fechamento_minutos', models.IntegerField(default=90, help_text='Quanto tempo depois da saída prevista pela escala a loja apaga as luzes e a personagem vira MISSING_PUNCH.')),
                ('hora_limite_absoluta', models.TimeField(default=datetime.time(23, 0), help_text='Limite usado quando NÃO há escala com horário de saída para o dia (não é teto da margem acima).')),
                ('evento_recente_segundos', models.IntegerField(default=120, help_text='Janela em que uma batida ainda dispara animação de transição (ARRIVING, RETURNING_FROM_LUNCH, LEAVING). Quem abre a página depois disso vê a cena parada.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetros do Escritório',
                'verbose_name_plural': 'Parâmetros do Escritório',
            },
        ),
        migrations.CreateModel(
            name='SalaEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador técnico usado pelo frontend. Ex.: showroom-1.', max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição.')),
                ('ativo', models.BooleanField(default=True)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('altura', models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(1)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.OneToOneField(blank=True, help_text='Loja física que esta sala representa. Uma loja mapeia para no máximo uma sala (evita ambiguidade na resolução).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_virtual', to='rh.localempresa')),
            ],
            options={
                'verbose_name': 'Sala do Escritório',
                'verbose_name_plural': 'Salas do Escritório',
                'ordering': ['ordem', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='PersonagemEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ator', models.CharField(choices=[('HUMAN_EMPLOYEE', 'Funcionário humano (estado vem do ponto)'), ('AI_AGENT', 'Agente de IA (estado virá de tarefas, futuro)'), ('SYSTEM_ACTOR', 'Ator do sistema (estado virá de eventos técnicos, futuro)')], default='HUMAN_EMPLOYEE', max_length=20)),
                ('personagem', models.SlugField(help_text='Slug do sprite/skin. Ex.: tina. Não é chave de negócio.', max_length=40)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.OneToOneField(blank=True, help_text='Obrigatório para HUMAN_EMPLOYEE. Vazio para atores não humanos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personagem_escritorio', to='rh.colaborador')),
                ('sala_padrao', models.ForeignKey(blank=True, help_text='Fallback: usada quando a batida não informa loja ou a loja não tem sala mapeada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens_padrao', to='escritorio_virtual.salaescritorio')),
            ],
            options={
                'verbose_name': 'Personagem do Escritório',
                'verbose_name_plural': 'Personagens do Escritório',
                'ordering': ['personagem'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('colaborador__isnull', False), ('tipo_ator', 'HUMAN_EMPLOYEE')), models.Q(models.Q(('tipo_ator', 'HUMAN_EMPLOYEE'), _negated=True), ('colaborador__isnull', True)), _connector='OR'), name='escritorio_humano_exige_colaborador')],
            },
        ),
    ]
