# Generated by Django 5.1.15 on 2026-06-28 06:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0005_pedidobling_vendedor_id_pedidobling_vendedor_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Loja', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('raio_metros', models.IntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local da Empresa',
                'verbose_name_plural': 'Locais da Empresa',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pro_labore', 'Pró-labore')], default='clt', max_length=20)),
                ('bling_vendedor_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID do vendedor no Bling — usado para casar a comissão.', null=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comissao_percentual_padrao', models.DecimalField(decimal_places=2, default=Decimal('4.5'), help_text='Percentual padrão de comissão (ex.: 4,50).', max_digits=5)),
                ('vt_valor_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carga_horaria_diaria', models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Horas/dia esperadas — base do banco de horas.', max_digits=4)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Login usado para bater o próprio ponto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BatidaPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida_almoco', 'Saída p/ almoço'), ('volta_almoco', 'Volta do almoço'), ('saida', 'Saída')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distancia_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dentro_raio', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batidas', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Batida de Ponto',
                'verbose_name_plural': 'Batidas de Ponto',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='EventoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('salario', 'Salário'), ('decimo_terceiro', '13º salário'), ('adiantamento', 'Adiantamento'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_folha', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Evento de Folha',
                'verbose_name_plural': 'Eventos de Folha',
                'ordering': ['-ano', '-mes', 'colaborador'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAquisitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('dias_direito', models.IntegerField(default=30)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_ferias', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Período Aquisitivo',
                'verbose_name_plural': 'Períodos Aquisitivos',
                'ordering': ['colaborador', '-inicio'],
            },
        ),
        migrations.CreateModel(
            name='GozoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('dias', models.IntegerField(default=1)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gozos', to='rh.periodoaquisitivo')),
            ],
            options={
                'verbose_name': 'Gozo de Férias',
                'verbose_name_plural': 'Gozos de Férias',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioVT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dias', models.IntegerField(default=0)),
                ('valor_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vts', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Vale-Transporte',
                'verbose_name_plural': 'Vales-Transporte',
                'ordering': ['-ano', '-mes', 'colaborador'],
                'unique_together': {('colaborador', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, help_text='Base de cálculo. Vazio = usa o valor total do pedido.', max_digits=12, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = usa o percentual padrão do colaborador.', max_digits=5, null=True)),
                ('valida', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='rh.colaborador')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='pedidos.pedidobling')),
            ],
            options={
                'verbose_name': 'Comissão de Pedido',
                'verbose_name_plural': 'Comissões de Pedidos',
                'ordering': ['-pedido__data_pedido'],
                'unique_together': {('colaborador', 'pedido')},
            },
        ),
    ]
