# Generated by Django 5.1.15 on 2026-06-28 17:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('alterna_sabado', models.BooleanField(default=False, help_text='Se marcado, alterna entre a semana SEM sábado (A) e COM sábado (B).')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='escala_ancora_b',
            field=models.DateField(blank=True, help_text='Segunda-feira de uma semana em que ela TRABALHA sábado (variante B). Define a paridade da alternância de sábados.', null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vt_meses_adiantado',
            field=models.IntegerField(default=1, help_text='Quantos meses à frente o VT é pago junto ao salário. 1 = salário do mês paga o VT do mês seguinte; 0 = mês corrente.'),
        ),
        migrations.AddField(
            model_name='comissaopedido',
            name='alterado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comissaopedido',
            name='alterado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_alteradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comissaopedido',
            name='manual',
            field=models.BooleanField(default=False, help_text='Pedido incluído/alterado manualmente (ex.: vendedor não lançado no Bling).'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='carga_horaria_diaria',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Horas/dia esperadas — base do banco de horas quando não há escala.', max_digits=4),
        ),
        migrations.CreateModel(
            name='ComissaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=20)),
                ('de', models.CharField(blank=True, max_length=40)),
                ('para', models.CharField(blank=True, max_length=40)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rh.comissaopedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissao_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Comissão',
                'verbose_name_plural': 'Logs de Comissão',
                'ordering': ['-em'],
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='escala',
            field=models.ForeignKey(blank=True, help_text='Escala de trabalho — base dos dias de VT e do banco de horas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rh.escala'),
        ),
        migrations.CreateModel(
            name='EscalaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante', models.CharField(choices=[('A', 'Semana sem sábado / padrão'), ('B', 'Semana com sábado')], default='A', max_length=1)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('trabalha', models.BooleanField(default=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='rh.escala')),
            ],
            options={
                'verbose_name': 'Dia de Escala',
                'verbose_name_plural': 'Dias de Escala',
                'ordering': ['escala', 'variante', 'dia_semana'],
                'unique_together': {('escala', 'variante', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='EscalaExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_segunda', models.DateField(help_text='Segunda-feira da semana afetada.')),
                ('variante', models.CharField(choices=[('A', 'Semana sem sábado / padrão'), ('B', 'Semana com sábado')], max_length=1)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_escala', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Exceção de Escala',
                'verbose_name_plural': 'Exceções de Escala',
                'ordering': ['-semana_segunda', 'colaborador'],
                'unique_together': {('colaborador', 'semana_segunda')},
            },
        ),
    ]
