# Generated by Django 5.1.15 on 2026-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_escala_colaborador_escala_ancora_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaladia',
            name='hora_saida_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escaladia',
            name='hora_volta_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
