# Generated by Django 5.1.15 on 2026-06-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_escaladia_hora_saida_almoco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofolha',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que este lançamento foi efetivamente pago.', null=True),
        ),
        migrations.CreateModel(
            name='LancamentoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salario', 'Salário'), ('decimo_terceiro', '13º salário'), ('adiantamento', 'Adiantamento'), ('outro', 'Outro')], default='adiantamento', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('dia_pagamento', models.IntegerField(default=20, help_text='Dia do mês em que costuma ser pago (1–31).')),
                ('ano_inicio', models.IntegerField()),
                ('mes_inicio', models.IntegerField()),
                ('indefinido', models.BooleanField(default=True, help_text='Se marcado, repete em todos os meses a partir do início.')),
                ('ano_fim', models.IntegerField(blank=True, null=True)),
                ('mes_fim', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Lançamento Recorrente',
                'verbose_name_plural': 'Lançamentos Recorrentes',
                'ordering': ['colaborador', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='eventofolha',
            name='recorrencia',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando o lançamento veio de uma recorrência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gerados', to='rh.lancamentorecorrente'),
        ),
        migrations.CreateModel(
            name='PagamentoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('componente', models.CharField(choices=[('salario', 'Salário'), ('comissao', 'Comissão'), ('vt', 'Vale-transporte')], max_length=20)),
                ('data_pagamento', models.DateField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_folha', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Pagamento de Folha',
                'verbose_name_plural': 'Pagamentos de Folha',
                'ordering': ['-ano', '-mes', 'colaborador', 'componente'],
                'unique_together': {('colaborador', 'ano', 'mes', 'componente')},
            },
        ),
    ]
