# Generated by Django 5.1.15 on 2026-06-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_eventofolha_data_pagamento_lancamentorecorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='recebe_comissao',
            field=models.BooleanField(default=True, help_text='Desmarque para quem não recebe comissão.'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='recebe_vt',
            field=models.BooleanField(default=True, help_text='Desmarque para quem não recebe vale-transporte.'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='carga_horaria_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas/dia esperadas — base do banco de horas quando não há escala. Deixe em branco para quem não tem jornada fixa (ex.: sócios).', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(choices=[('clt', 'CLT'), ('pro_labore', 'PRÓ-LABORE'), ('sem_registro', 'SEM REGISTRO')], default='clt', max_length=20),
        ),
    ]
