# Generated by Django 5.1.15 on 2026-06-29 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_colaborador_na_folha_eventofolha_natureza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerancia_minutos', models.IntegerField(default=10, help_text='Atrasos/extras dentro deste limite (em minutos) não viram saldo no banco de horas. Ex.: 10.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetros do Ponto',
                'verbose_name_plural': 'Parâmetros do Ponto',
            },
        ),
        migrations.AlterModelOptions(
            name='localempresa',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='batidaponto',
            name='ajustado_por',
            field=models.ForeignKey(blank=True, help_text='Gestor que incluiu/alterou a batida manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batidas_ajustadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batidaponto',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Loja onde a batida foi registrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batidas', to='rh.localempresa'),
        ),
        migrations.AddField(
            model_name='batidaponto',
            name='observacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='batidaponto',
            name='origem',
            field=models.CharField(choices=[('app', 'Aplicativo'), ('manual', 'Manual (gestor)')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='lojas_ponto',
            field=models.ManyToManyField(blank=True, help_text='Lojas onde este colaborador pode registrar o ponto. Pode ser uma ou as duas.', related_name='colaboradores', to='rh.localempresa'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='registra_ponto',
            field=models.BooleanField(default=True, help_text='Desmarque para quem não bate ponto (ex.: sócios, CEO).'),
        ),
        migrations.CreateModel(
            name='NotificacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Dia com batidas incompletas.')),
                ('mensagem', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em análise do gestor'), ('resolvido', 'Resolvido')], default='pendente', max_length=12)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_ponto', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Notificação de Ponto',
                'verbose_name_plural': 'Notificações de Ponto',
                'ordering': ['-data', 'colaborador'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
