# Generated by Django 5.1.15 on 2026-06-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_parametrosponto_alter_localempresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosponto',
            name='intervalo_minimo_minutos',
            field=models.IntegerField(default=2, help_text='Tempo mínimo (em minutos) entre duas batidas. Evita registrar duas vezes por engano em cliques seguidos. Ex.: 2.'),
        ),
    ]
