# Generated by Django 5.1.15 on 2026-06-29 01:47

import apps.rh.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_parametrosponto_intervalo_minimo_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('folga', 'Folga'), ('atestado', 'Atestado'), ('falta', 'Falta'), ('outro', 'Outro')], max_length=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('remunerado', models.BooleanField(default=True, help_text='Folga/falta abonada (remunerada). Desmarque para falta não abonada.')),
                ('anexo', models.FileField(blank=True, help_text='Atestado/comprovante (PDF ou imagem). Imagens são convertidas para WebP.', null=True, upload_to=apps.rh.models._anexo_afastamento_path)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='rh.colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afastamentos_lancados', to=settings.AUTH_USER_MODEL)),
                ('periodo_ferias', models.ForeignKey(blank=True, help_text='Período aquisitivo de onde abater os dias (apenas para férias).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afastamentos', to='rh.periodoaquisitivo')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ['-data_inicio', 'colaborador'],
            },
        ),
    ]
