# Generated by Django 5.1.15 on 2026-06-29 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_afastamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('prop_entrada', models.TimeField(blank=True, null=True)),
                ('prop_saida_almoco', models.TimeField(blank=True, null=True)),
                ('prop_volta_almoco', models.TimeField(blank=True, null=True)),
                ('prop_saida', models.TimeField(blank=True, null=True)),
                ('sem_almoco', models.BooleanField(default=False, help_text='Funcionário declarou que não teve horário de almoço.')),
                ('observacao', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando aprovação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes_ponto', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Correção de Ponto',
                'verbose_name_plural': 'Correções de Ponto',
                'ordering': ['-data', 'colaborador'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
