# Generated by Django 5.1.15 on 2026-06-29 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_correcaoponto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('sigla', models.CharField(blank=True, help_text='Ex.: VA, VR, Plano.', max_length=12)),
                ('eh_vt', models.BooleanField(default=False, help_text='Marca o Vale-Transporte — usa a tela dias × valor e entra na folha.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Benefício',
                'verbose_name_plural': 'Tipos de Benefício',
                'ordering': ['-eh_vt', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='periodoaquisitivo',
            name='abono_dias',
            field=models.IntegerField(default=0, help_text='Abono pecuniário (venda de férias): dias comprados pela empresa. Abatem do saldo. Só liberado após o período completar.'),
        ),
        migrations.CreateModel(
            name='LancamentoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='rh.colaborador')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='rh.tipobeneficio')),
            ],
            options={
                'verbose_name': 'Lançamento de Benefício',
                'verbose_name_plural': 'Lançamentos de Benefício',
                'ordering': ['-ano', '-mes', 'tipo', 'colaborador'],
                'unique_together': {('colaborador', 'tipo', 'ano', 'mes')},
            },
        ),
    ]
