# Generated by Django 5.1.15 on 2026-06-30 20:38

import datetime
from django.db import migrations, models


DATA_INICIO_PADRAO = datetime.date(2026, 7, 1)


def limpar_pendencias_anteriores(apps, schema_editor):
    """Remove pendências/correções de ponto anteriores ao início do controle.
    Tudo que ficou para trás (testes de junho) não precisa ser corrigido."""
    NotificacaoPonto = apps.get_model("rh", "NotificacaoPonto")
    CorrecaoPonto = apps.get_model("rh", "CorrecaoPonto")
    NotificacaoPonto.objects.filter(data__lt=DATA_INICIO_PADRAO).delete()
    CorrecaoPonto.objects.filter(data__lt=DATA_INICIO_PADRAO).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_tipobeneficio_periodoaquisitivo_abono_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosponto',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2026, 7, 1), help_text='Pendências de ponto só são apuradas a partir deste dia. Dias anteriores não cobram batida nem geram correção.'),
        ),
        migrations.RunPython(limpar_pendencias_anteriores, migrations.RunPython.noop),
    ]
