# Generated by Django 5.1.15 on 2026-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_colaborador_canal_meta_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='correcaoponto',
            name='campos_aplicados',
            field=models.CharField(blank=True, default='', help_text='Tipos de batida realmente criados/alterados na aprovação (auditoria — os que já vieram do app não entram aqui).', max_length=60),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='canal_meta_individual',
            field=models.CharField(blank=True, choices=[('show_room_sp', 'Show Room SP'), ('anaca', 'Anacã SP')], default='', help_text='Canal cujas metas individuais alimentam. Deixe em branco se não tem meta individual (ex.: Cris).', max_length=20),
        ),
    ]
