# Generated by Django 5.1.15 on 2026-07-09 14:44

import apps.rh.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_correcaoponto_campos_aplicados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfastamentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.rh.models._anexo_afastamento_extra_path)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('afastamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='rh.afastamento')),
            ],
            options={
                'verbose_name': 'Anexo de afastamento',
                'verbose_name_plural': 'Anexos de afastamento',
                'ordering': ['criado_em'],
            },
        ),
    ]
