# Generated by Django 5.1.15 on 2026-07-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_afastamentoanexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_abonado', models.DecimalField(decimal_places=2, help_text='Saldo do dia no momento do abono (positivo ou negativo).', max_digits=6)),
                ('motivo', models.CharField(max_length=240)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('abonado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_ponto', to=settings.AUTH_USER_MODEL)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_ponto', to='rh.colaborador')),
            ],
            options={
                'verbose_name': 'Abono de Ponto',
                'verbose_name_plural': 'Abonos de Ponto',
                'ordering': ['-data', 'colaborador'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
