# Generated by Django 5.1.15 on 2026-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_abonoponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='afastamento',
            name='dia_inteiro',
            field=models.BooleanField(default=True, help_text='Desmarque para um afastamento parcial (ex.: atestado só de manhã) — informe hora_inicio/hora_fim. Fora desse intervalo, o ponto continua sendo cobrado.'),
        ),
        migrations.AddField(
            model_name='afastamento',
            name='hora_fim',
            field=models.TimeField(blank=True, help_text='Só para afastamento parcial (dia_inteiro=False).', null=True),
        ),
        migrations.AddField(
            model_name='afastamento',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Só para afastamento parcial (dia_inteiro=False).', null=True),
        ),
    ]
