# Generated by Django 5.1.15 on 2026-07-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_afastamento_dia_inteiro_afastamento_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoaquisitivo',
            name='abono_data_pagamento',
            field=models.DateField(blank=True, help_text='Data de pagamento do abono.', null=True),
        ),
    ]
