# Generated by Django 5.1.15 on 2026-07-25 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_periodoaquisitivo_abono_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gozoferias',
            name='afastamento',
            field=models.ForeignKey(blank=True, help_text='Afastamento (dia inteiro, tipo férias) gerado automaticamente para dispensar a batida de ponto nesses dias.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gozo_ferias', to='rh.afastamento'),
        ),
    ]
