# Generated by Django 5.1.15 on 2026-08-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_gozoferias_afastamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VtValorVigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField(help_text='A partir de qual data (1º dia do mês) esse valor passa a valer.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vt_vigencias', to='rh.colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vigência de valor do VT',
                'verbose_name_plural': 'Vigências de valor do VT',
                'ordering': ['-vigente_desde'],
                'unique_together': {('colaborador', 'vigente_desde')},
            },
        ),
    ]
