# Generated by Django 5.1.15 on 2026-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('nfe', 'NF-e'), ('estoque', 'Estoque'), ('produto', 'Produto')], max_length=10, verbose_name='Tipo')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('payload_enviado', models.JSONField(blank=True, default=dict, verbose_name='Payload enviado')),
                ('resposta', models.JSONField(blank=True, default=dict, verbose_name='Resposta')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Bling',
                'verbose_name_plural': 'Logs Bling',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BlingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Bling',
                'verbose_name_plural': 'Tokens Bling',
            },
        ),
    ]
