# Generated by Django 5.1.15 on 2026-04-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blinglog',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico Bling', 'verbose_name_plural': 'Histórico Bling'},
        ),
    ]
