# Generated by Django 5.1.15 on 2026-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0003_alter_blinglog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinglog',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('nfe', 'NF-e'), ('estoque', 'Estoque'), ('produto', 'Produto'), ('contato', 'Contato')], max_length=10, verbose_name='Tipo'),
        ),
    ]
