# Generated by Django 5.1.15 on 2026-06-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoBling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bling_id', models.BigIntegerField(db_index=True, unique=True)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('data_pedido', models.DateField()),
                ('cliente_nome', models.CharField(blank=True, max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('situacao_id', models.IntegerField()),
                ('situacao_nome', models.CharField(blank=True, max_length=100)),
                ('forma_pagamento', models.CharField(blank=True, max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido Bling',
                'verbose_name_plural': 'Pedidos Bling',
                'ordering': ['-data_pedido', '-bling_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSituacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_id', models.IntegerField()),
                ('situacao_nome', models.CharField(blank=True, max_length=100)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_situacoes', to='pedidos.pedidobling')),
            ],
            options={
                'verbose_name': 'Histórico de Situação',
                'verbose_name_plural': 'Histórico de Situações',
                'ordering': ['registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='BaixaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baixa', to='pedidos.pedidobling')),
            ],
            options={
                'verbose_name': 'Baixa de Pagamento',
                'verbose_name_plural': 'Baixas de Pagamento',
                'ordering': ['-confirmado_em'],
            },
        ),
    ]
