# Generated by Django 5.1.15 on 2026-06-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    # Pedidos identificados manualmente como permuta (não são vendas reais)
    NUMEROS_PERMUTA = ['9534', '9157', '9948', '9752']

    def _marcar_permutas(apps, schema_editor):
        PedidoBling = apps.get_model('pedidos', 'PedidoBling')
        PedidoBling.objects.filter(numero__in=['9534', '9157', '9948', '9752']).update(is_permuta=True)

    operations = [
        migrations.AddField(
            model_name='baixapedido',
            name='data_efetiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baixapedido',
            name='forma_efetiva',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedidobling',
            name='data_corrigida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidobling',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidobling',
            name='forma_corrigida',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedidobling',
            name='is_permuta',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_marcar_permutas, migrations.RunPython.noop),
    ]
