# Generated by Django 5.1.15 on 2026-06-24 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pagamentos_permuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosituacaopedido',
            name='situacao_anterior_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicosituacaopedido',
            name='situacao_anterior_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricoDataPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anterior', models.DateField()),
                ('data_nova', models.DateField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_datas', to='pedidos.pedidobling')),
            ],
            options={
                'verbose_name': 'Histórico de Data',
                'verbose_name_plural': 'Histórico de Datas',
                'ordering': ['registrado_em'],
            },
        ),
    ]
