# Generated by Django 5.1.15 on 2026-06-24 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_historico_data_situacao_anterior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=200)),
                ('forma_pagamento_id', models.IntegerField(blank=True, null=True)),
                ('baixada', models.BooleanField(default=False)),
                ('baixada_em', models.DateTimeField(blank=True, null=True)),
                ('forma_efetiva', models.CharField(blank=True, max_length=200)),
                ('data_efetiva', models.DateField(blank=True, null=True)),
                ('baixada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_baixadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='pedidos.pedidobling')),
            ],
            options={
                'verbose_name': 'Parcela de Pedido',
                'verbose_name_plural': 'Parcelas de Pedidos',
                'ordering': ['pedido', 'numero'],
                'unique_together': {('pedido', 'numero')},
            },
        ),
    ]
