# Generated by Django 5.1.15 on 2026-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_parcela_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobling',
            name='vendedor_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidobling',
            name='vendedor_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
