# Generated by Django 5.1.15 on 2026-06-23 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nome_bling', models.CharField(help_text='Nome exato como aparece como vendedora nos pedidos Bling (ex: TINA DIAS)', max_length=200, unique=True, verbose_name='Nome no Bling')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetaCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('show_room_sp', 'Show Room SP'), ('anaca', 'Anaca SP'), ('atacado', 'Atacado'), ('site_instagram', 'Instagram / Site')], max_length=50, verbose_name='Canal')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta (R$)')),
            ],
            options={
                'verbose_name': 'Meta de Canal',
                'verbose_name_plural': 'Metas de Canal',
                'ordering': ['-ano', '-mes', 'canal'],
                'unique_together': {('canal', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='MetaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mes')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta (R$)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='metas.funcionario', verbose_name='Funcionaria')),
            ],
            options={
                'verbose_name': 'Meta Individual',
                'verbose_name_plural': 'Metas Individuais',
                'ordering': ['-ano', '-mes', 'funcionario__nome'],
                'unique_together': {('funcionario', 'ano', 'mes')},
            },
        ),
    ]
